---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgC722PvXs3x1av22DByfiUCnDXZNagSd/QzDz9TESMpjMpZ17QDW5bFNRi31dGy/aXse8vev5h7Y/VcWQDvn1n9e8/s6sdBvgaFWZzagCv2J9qu8MOQQ8AblxKTYH6WFTUNUNjLy+GXZWsIC8v80Vt74ujOAIL4fErFgrgV+KIjcAUeimrUDjqomIR1n6cM4igYUSMw/9FEZYBdX/DhMio7LuwUBqGCYimCS2aLABvCPAYdvYcq80XwqRkzQxkpwlgVHwhwELuOR7nSukWmjcx1Bwz/uKNNKF3ZxgPwN80gP1z3w5EwIztPr9YCLSYNObajxzQQJ5Hu1nSrHCb2g98ugXEY654C4dM2j1eYgJP5XMea/qly7+x81pLob9OAEaeYCNI2mA3c6atmhTKriPlPrY+xlaUdoWBhdz3zo67vCXOFkEVu0WWyJ9t07xMdkIYfSfROLox2265TtxdY3NqBYKBgs2oX7QrwxuX5HnroL3S5Z8yhaW0OWTpq/ObN9I8yuVP+ZVw00/mJi2sOTCPNLKgFeDjYFxIzkceLxiItAHjCZMWnIwjuPryygr4qyR2LeiJE6fcH6elKE7L21jsC9ytvGjrMwYuKQzfcvAiBTeqleSx5ynDhklH8PiKyJ7VYXx576d/RPyOuAxj+O9WFVUnsweuTGoroK0eEEp7zm9yqBlM1V9VZokuR9kDdKujMEk1ISSkmWeuQkOXryBnkUlb90yz7IuFRB9bx8n1HSjNf7IRp1uVMv7VtDcJNDB8wX0V4k+JVpSG6+zyxm15jlxH7o+u6LujGtsWw9htLW2pX5Frbn/qjW06qIxRX32OzorsVaCX1RIv47IgEepRhWaJ8uxL9+XFXoX8lRGC4Axkbu6zNfuzZDEuFcPPeqOq73x95uHWsFdtC6gYG8LWRbHkTO+hjClQ2Sg1gwU/wo0DrxlgUM+JAgXCsEGFFZjxaWayPf59Ym+4hKLyogCW3RmToZDk1FFzqRugzG9fbI8CEEpEdR4k=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson
