---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgBXti7Jx1hIkr1khxxksfo4NNj9atLx4dd/ALWvrOYJ899NPfqL19MjaEyCi6xPhqbEbX+K/T073lAiBFN/D4Yy/e6/U9wAxreoJT1m1qZZR18+ec2G6+Z05A71ykv98kjhtmL0Lo4Wwk7vjCyfwpTzrTdSS4+FPFxtxtSTMmIB40oKfu47OYw306N9tOvIiroBUWATL6vUuzdhe3BO/OnDw7ziaolQ9EmHCmqM5Qxzu6hwOMyyEIzzyhxinxPCIBMJib9PdGC8MYpDzXf4q/5kcHmKwtpJ8aR6j3bQYFaX7NEYbFGjkZEufz4AoQcu53yH70vlvd0lH/r0QbHNm2ifRVa9S/9ZKzvTDMqP4BQRzi7HINEgQb/3HOWFNnBGG2P2ASlaziug/lh0ySD3DtFnLjil74WHIeaadINMv1U4Do9mZFfChG1Gg8JsFhunrMTt1rDkZbcGW5W2dmanidUkQ2q8MC9NP1gbiGaTM0sKZns4nzG8tisEUbMPZU9/9DDlDa+gjy8KPaaVlSW8oIj14YBm0nhPIzZkxXyvUtszYCs6t3u9rEeLShDBOg6XROWgtRfenNngbduoO6bdGC2HyTmuFudn9cExFCLSTvk8rVtJ50dVNhZBy2M43Bw5OqMmd413D9DAGKsMsfam1qDhwcwyFFhWlx6AW8VfQcYGcS5vsHGBYZKb3GS2NuN6GXRkZB3vuder+VqGgpO/XTkoZLi3qMQvs2ceoG2vdcRdGNejxKSrT/Vw6uMMpRe3yDewqpVYF4c9JxrZYnfxD1TR1MR9ovxs4hL/AhUEuQSo+BBj+g6QUSMiyJKlVw1fioOVIgoK8Na4UNw1WPNrfVbXSHd7vCxGTavXliSTd1yPhppK3H6bj4hnr+1JvQk3yYxEX6PyVLD2E22V+kIealpOSSP+omYdGniOy/wlLDaeoYiFMXqGq/NC4o2AKDssMIYzkR/jvAhc6NukGkuQDTWYYJPgZo6uoFC7IfwxrUMfExZSH07ijnQ=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson
