---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgATN/FBRVTOI6vTGEd1qZz7sswi7IAROetIlvhpa8bPkAepAaCR9A3dwNSx+ghfen1sdGwNYvfdyYo43YkZSzdbkvsSfydKcO6KU3+oMPsa79aC3e/64ybqPVq2mSdKEvKZqe9cUF+w6vFCkg0+lW6Rbpcv1xOxdAiuSokw+X68gYioM7TyoxYV/cCSeVjZE98K/xJfttQxS9PU0N0/A62LfQKnnHxth/aW+Dma2aO5MV16gcKQayO7nPfkAwl6RQFYOhMeqOXlbaEF5ncWKQYYKwgpm2Pd4WerXoWQwT74ssx0ExH44P/FxzlTK8aF7AKjnIJ0aMHcLANXLLuxWijFVHV7kfIIM0O/2llb2JME9HSHhetm9QAPdzHjbmUfJVg2HYjOR9yy+l5Ts6vlgtk5w2b3EP3ktMyZCYA/t7du/xnVeo6XKqhq0+/XqLPnfk1uA5j6gJ0ixt4HX3jy7t2vJLS9c4plc4I77MN31wu9WEA7RxqJ2zTvFTyS/uEW1ISINrKvN1ixCrJJs5QrMf6f2K82sfz65Utept4k0JCUG34zRbL7+XjIXJ4NKxRifgUiLw1MFn+EQUgab14iny/vXgxjFB3ubBlgKjkso68DE2Yg8yEHH1lSchsVslOlfSXn5eZLncThaNrSkx90wFMT7lM36lXVv663OzfP8LpxiZrAU0B3ynkPNjMMj6raGVECL66euYixJyHkWhKYGMP7BcPgSiOqu6bQtAnPSy7FkUiMwTTnYgXw4ZrEOW4JgZghAyKfcpl/0qW48O/MlUftQn+ErS8eBFCyzc+s/3PKcxFomP9wqYpl9nYpq8YncAZqaRnJ3/I6Y7NViBCEIVb5c4aHK3gpMQUz3gjI+OF1m88rNAyYGvj14Gb20ZwhpD1WagSGYPb8iRvLja6P+SV5ySWeNiq+kjWJC9e/rnDfJSGdd3Hq2A8LfFusO2noUoo3F9YbHwoNrCpIbwC4umECtf7pwEGj+0HqoEBE7Jx2qk1540VvhE4=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
