---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgByO9nalpqN1G5VlJuyR6ah5ZilJdFw8N9+tbwt6zny9wCMNSc0j8vbfdTcxRdEEvSywhIiqLBIl0vHAdFcXCV4lzEvPpj2wJHQBYXV7BWSb8BX/zfyFlUaVQSuH/KFofWkcAQ3dSKyddt7ykt8xOlqgmcpQc6fqj+IrGxnxXCKK53MJmfdA2dspr9oqGzQvHdVdPKoavuMchrK37uXKbQgB302yhZ+MC/fv9t6Tz9d9503F1Vq3oCDJsSyjb0042N6VyoiF21LQt0JtJvLlRjuBISXApTxn/4y8NUWErwpIlNoNvRqYyMywa4RoV1459HtMdcGtIRmnLcwNl73TQGIZbvpEz5HtFS+SKq8Gjyr2WXu1oXkdmM/eYN2D/xSax8Hzqxqczt2SXqJ4Fdm22JXz7nr3bbgLSKuQynR9kuasOl/8erF/LnQVsFcsUGcAHlpqkgS6549GcuCfjPGPa+2LaptNA1TqExOJtekddtcIdaICnLiaD01i7whbWUtUMxtCqZaSFrpPV+s/+vyBBifKiiHuehTG6CqoPmDU9ApTlNB4ylYMdMV2+SgAvM5hNYh0FKsMawO4kvNC4/IS226VTpfxaIbh5ZEVOReBbilLAiaIZoJKJNLj0cf8ox2KFFQexmTJ6HUtK6invO4ISht3kp7oYcksKpIclqXMEiRYh05X6FhtTAKmmsZeccUufVhCVYOFf5p4O/QIbb/bwlXujmVrSCxCKLLDnQTQyeU/akBQvhV/1tzYmc+BOW8ofV81EwF4NuUykpU0KqITc6hnXB3F38QHkpWRnFqieSvLr66AENahBXatz4ARwhOeO87hFTqmQ8L7L28M0xMASDBYYG3rpAlu2D7LbnjmOo6TFggsqM0tsOyM3Couhab4hNyNF4tVuFbVdiEJVYxQC7Y1DvN9xwPrEhaXZ/peZ7j+rxIYoDLLbb4x0NNL32VJ0WEQ+xnS+nLLOzV5hsZ51YjNutkuihvtSJn4KhkBKQ4ceq7iIbrRnE=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
