---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAHH6tQCG/8zYvhRqTqIS7raujLuEB2riOkWGXmUCsdtZqI2QpqGMXUm5tYJJ6byKFQYQgbZnGRMc3IOW8VR1xjqH47WikrQJw5hM/6NIQSGvBihrSOIEMU7+tB0FynY1mWYG88zvzEuY/GwLNmyTQdc/Yyq8b5oV4wLk4+4kiC38I7RiUiiBI5cajL6HZDA6X9CFjXgeHui/gy2As27vYca0KWsWs34C2nTRf66Yy6HdJGiyTTgQpiLXhYqktwbubEEW/a2l8try9tLtgVtO9Uncf8PbFnzUjsjdGDdAafl39Onpv94n6fWW+jiWBWeyRjx+RRlmxkhhdFAC4FGg8RDZ5QTRmvO1yzCJm+ORtk/Nhi6+0VlxCQpGbeek7+rO8M4gIy0Ucd9ZASH3wbngtwqOSgTgm6CnAhI1lOCgbjtV/0i1/WJRuZbYfXLjBiJK2E860ninWYgZK7BQwGAOCqSB2BU5aoMdfu8009QkVsDsABsSjFnCliPMHNQ9GiywQaUKubJJSOEpjEzz198b5GGzOrUgOh2Y9pDPSMb+51GfRPyIFK2bjK7UBmD0pvytzHGggKm8t+6V+em3mZ34f75dgNZtWfFRm/9Aw369hLTCrgzntv0X4bXuA+0G4qKPYi5e14yvZkzslJTZQq4a1crQ3k8tWcMTQcf5T6lyufLcaZj5KdOxhMaP/zkc24JeZjv0aYD2T7lh06EvdekKpllk+l+Gfu6midCbdhnheqwpQ01nWH1ux5DqT665yrUkb2P6wt+UJKgJ5Kt/0olUwleEfG2QHOSMWFR4PvDa0puyU=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
