---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAkHGwUNEhIauzC6pcpjfE3BlcIEcEBWZwMO/4hF3i4nWCquzyz/36DVVUcHDB6QuMoGBP28JqfKIehl+LWg44TDCnT0YHPBq08eCPcSs6K9q08wmrfX5Tc81y0BFrZNR5WapnM6j75LBWprZ/V7YvPPqrxjiF3HI4w0wLuYqtxxXoArnN3y4ez4E2foBIJnPf19qRI9k9Xh/FpHFUZ15Zk03DAgrE1T2xdlpiO79qMD5PVW6StRIWamr/en8z394olrtxVIfauWP40aBlgVFdOCm8dmDZQp4Yi2kgozBdzD3Z3nQKMQNlelAin6qDr8wB+55vQaBGzlJQ5fd6RH8Guwrst+ndQ+t9jchUUxbMYsnUPM5j782+cTVVzr+S7veutRJsFyMdDZlwI1IXi/7VkiXaHiY2NUOSfaIMmSlrw9WJbX0FqjzZWWEuvuTFgNOaU7/nYudrchgf2OU6gMysyyA1r96JyIyxziqS6q3wbArjXP3sKNWynVES3GdmTXvdSlp2OQB7JXZ0R5kIoO+RKMv+KAnpb/pBHMyZqzACCNk4WjsT5QrrYYhDGcg7kEP7c6j9vDWn8tqT5r6VzPdiiipqZ2sjaMdPGxulecMVENwV+Z2umZXKWF1ux+uwdzUdyMUPp4wEcMkeSFjOhp7bh4oUPMw8/WEvuHkQLqYRrpXcjleO3QZrmwSAzl5s/5/tFxkOjzjUjmNpsASnLz41Uoo7Fz0zp2/DxXqeASp41AyuAO3lod5JOoA55fFb5imUpRcIfgVcUcpk9xLmZla4kg84IhrJHMftbpJ+8ks5PS6k=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
