---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAzf+V8ThtDV2dbDKk75txq/6lBun/D/TtAD9aHvgsEdcg9APLxJ6Xy2hEyeqqK/07a2uhla/5gFYfDFBTO6r5ET8GQA7+nckAhIBz0QnxGwFliUrzVfSkwgrZ76Z7piGrPuAUgZybZtF+Pf0gZzr8P7KoPloW2U0Rm8ZKrXPMsSXNz7XMd/dgiLd8wuIo5yr7phM/n853JiRJygF4gGb/AZ9lcSlb0hgAOyc+eWxqlN1GQZzYJLUwu8Lmwt23B6bZxb/0KjoBrLHxUMwBDf11UUoXS7H/ReUifwFbLlCyUFOPBDKHlFYRuvjfaXxslJoPkneOIjGCLVIQSN5BIXTNlVoIYdoYGj5Fdj+mqige7u4vX320UEUfD+S1+sNuWNwkG8hnZNg9cCLzEP+0p65fZvkPL7INr6hMCe5ZUJu+FeX7A84A4ivkJaYmV+le7MISl55MncSKtrvDKqwHtrhSsSuo5RXbz/xVCGSw9j33tEtscw7803YLpxbqxY5YPq7tarmvM2m3Xc69gGjEbNwF1OoRBuZ2Wu6oks5I7BarwHdG4Cc9fLuz7f2PEL3sCCzFMeHh7HX8rUhPUpOPv6MIYPAdHJi1VsDrC79HaPrPWtGW3sRwC7AFYdHlEIACnJZ6dIC94vbbV937P6zf0R0f/lfami5/NWIreFpr2+m0cA5/aMBr9jnOLzNgO0xq5Xnm6oxTsKgOxrnvy+YB8ShlximDyFtC9tDg6vUgZshlwrpQwEHVxt5mm
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
