---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCqkc+wcSqf+Bphpnr6sYAKQoYMDHJtIvu//rpFvbuRHBwMdtVW7tbSX2b3hp1t2b2aJh0cwemZLo4UTtqjrDA24fp6VXeQ2Q8KePaMjBpOA0nVsAy1u/E7HgTp38fbYisV9kT9hsIlncZzKy3muLdWETouCoLr+ikz/4Dj81qFGWmVZ9RBmMMAKzvNF3En39d1GzYjJpoi3ViBjNqivoW3886cBm4Aog7iFHCLx92Uz850AwEtLClEy9HwKCxwMswmMLfrcfSZ1QX2cBUJ37ky3CaT/U/T7T5ykg/B9tGWaunYFdyDtUvAnTLIjofKHRKV7zUM8lx4NBd5Z+hCjF6ApMY2OGAfyZPM69+xTzKHYwZEjH+q5/XJoaaEGZCdaF9fJmgy99LcVlnTnctAzM2LR5h4hyyGip7PT8RaFSinhzFqk79CjtViOfmVVouK0kMjOSkFKe3yH0ZW8zQeoixhd8Pqwhd2hv6IOpoy01kIpbDI3FBrmrCtnQEjjlR9GPuNkEmjFIFV6JDP2994phsD+KBW9uF+XEUEDagyD66lunUQN/PY0SkW3TorPnJzHqrzLgJa+Ge+6i+NzaApkjg4G9qZisKf1MNnMrxJclUipA+53eB2E2S7irDIeSQsugAZeS+PLQX8Vb6jJaygkMEknWPw74meqmvC5EWLDRl36xgCymjU9coNev+pq7IugRz3rpam+6qtsFP+k/nbz7X1v7mjJhwPU/dcq/n0tSU442KsponwISqh
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
