---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBXofzHkdYkHGSOImuiDd9GnP2d0lV4e1OCmHDU/Te5KlzqANxPP1w2COvh/aTdwuknVx0tWUwG+4xRTCmtMB2JTaLmqqLQrbV1KD28Nt+1oex5ZKNmVLqmHNu0c9LhG+Y1UHD9AaVCG55wg6pQ9Dnp10IHe6M0+1g5h35pVGMPbJ7BzzkHoUPl8yLcNqeBzT2S3E5KfsBMFzrLTiq86wKBqggLHVrNn6yQEfmMXWY9G46vWrmHcBh0+o9sc6038VP/QKq21zqF5cc0ipbtyUzVyWC4sPA5MVx8jY04X2L4MIQVc+V4f85RKKnAJBNbMFO8zTY9Bew5BeiKF8yh+pyBmWfJiwcbPvyZ8C4p9EV/4tihbNQvwJTKx/yVId/cJnYfHpOHqsL0nQZvOPW3s9KWTVKlPTWtuYn4h3pNMeMqSPE2GpyEzpsCUIPFdKjlZdjV1SaB4us8UM8hNwC2v+dYclBBKqwXQuJRDLTA3e7cvU1qV5CtZMkZ8rqiah0DZMyIfd5YrG4/XQc68K03DMsFWYXiStpjYXNWcvtB5f00CgiwCrISZhRrcd+O6ysTm3nRfdcfZcnVCaY2DsnhaSc7AgY2K1PF+iRyKA1lxHnq4v5KY9gibbOJov3+LwSwKZA5oAIBi3pIBBeZlhxoY2l+grKIrFaB24SNpuZFOEsGBJfzmq8vRH/1edCrv5/HSb+BKS3xYfgHId2UE8ZqH1GBloGsjw2B+yaHA5qqjN6C3qipNbFl+Xno
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
