---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-auth-secret
  namespace: flux-system
spec:
  encryptedData:
    password: AgDEprHnnCqz3XqmwNeQLzKxqP4eaiVeABzrgVe9eH8VyRxgAUI0iKmikl1sEQW4qTpK4ZrBBTljNG6iVrbAnWeWB79lI4DtK4BuWufdwCFESOGmi90pRaops/b5rOfWOG+Y/IUMGFvrZV6edSGsl3s7eT46a/BKAX42JCgUEF47qRuzi2QX5qhobeRWxZDOpnawbBIGrPUYlNdzdWyYGVBxL57QJMeZuGn419Z+ylcVlCTkNxDrlDFTgTzCquiahKrS2ndf9fX4ww4oFt8pqqtxas8r2mdG3RZGqwn88xPiFAXQYBS9yqcPZLWabVJu1VdDafXU7IAeUp8tTjKtcQBn+KkrD9NJl+XEpuGnb78LQQEjwKHs24x3NFaimP9fvhkFDsN4+aObFKyXSsnDSe7uQXkzZKRfmKxiyrW2+m8L05KFb3vVA1eO9eZbxRB+nWLKq09V2DLjY779OHMjsx4xi8pQIzq0Iz6gX0pcl2VG2txiI+ytOcF5LBNU6QX2yIduZtVzUSNrdTT/sRhTPnorpJARDtz1p61cro6fjLcyA4sKLGB404T/R25Ba7LCpjSIjrGl07uQfx3+mYdO3mGG9RfmacCiK19M9j/7ymmQuX2ZpRwzdasEBZEHJk8f0PUm9tQ9rnsH6qKsn4zOS7tOK/Zs45wzmoBi50QKxWXIU8++CNsrj3PL5KyPiBXaGghVxmsPOiZ2m9kSB45sTnwSp9uKeqsUanepuFeYbi0noGBLuEY9rCF5
    username: AgC9Rr+pITaL4+/NdQ5x7YphxDhYdBYg/KE8dRHENblpgashnqxMClfOkE3wOGnvJ9+BdCYPy+tiQAYWqQBYbWzbppou5da0PQdD3kHtE1+v1JFAaphWWS1d/u70okGWgStxQmFSxXOoPtwL2KX56Xfs7T7G992xVYXOf0tjfnGcAc1ORpLD1svTvcUMGPcobOYy1tZjwLD0YEndSpq/7QGD31RG8D8IfdHzAftj5PdNNWL+UfZ7FZLXhojPLbabrirCa46rq68fSmrr9HvDD1EzwD6YqlYA5/RZ9oXBt83fmUAkzqXhLiLi1F7XtUcnww8yPbgIsWL6xkrz/u+2hqgeI16lNju2KCLlxuIFDdEvVn3zIAXgn1HN+H563lpZeC/yavnK7xsXlF9CUTNnZNObUwVFnMzURbN4+0coiO/HcPGUMcXDjemVDzOlLZOkRwcZcVzt92u/nRhR6OuStHUIp5M86DQVaUtS5F1tBAGMAdkGRlwnokvKR56ql5Whu8E7hprkuiqWY1Oc4Nmi+P5yUxfbjdFaC25xK3P5WTauVT1PUMLdEKQcni/0Xn1WLPi2LNpT8cUv2HGPTYgq3L5uhie5PR2gau0dC6MZ2ueyfpdc+JgZzM9jdCfdxYy1RheVW+Dy7n5Zm59BHbVgt3Z5h0WHkrkRR3mlfmWCiNrPXelVEXWtZ22orC91CuRMSdYuoHU=
  template:
    metadata:
      creationTimestamp: null
      name: github-auth-secret
      namespace: flux-system
    type: Opaque
