---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgAv83vRzf8OKgsrbRLd0+0yYoGhkmB9us9eWrYonKLCfwY7DL4OWq4Q922e90EfXqRaHRDLff+s6czC0NyC7QZdNLKqEX7tSOnZfog9kBTuUG1imnTJskTsyHzBDlTN+vXvhIMIbowIl1cJi5ZpLR9M4FCUnkWymSrgvbfmooYmR/r1YphyzbNoy3T4ThCl98N+Pa2YeT1SuBk5r4MWgfJu6Tf6NVAGRq60uN9XNzF3cFGSnm5iwOLlbUc6GZVxQfc40iz2jzfE/d+v8TZLKBsyAUlwdsUuayEVmzStaCJ0VLJscOa5hqwfI5zT8PBQdH4y8IXxq/7+4OwF0Zln5wlX0pIe/DmJf6dclFsIs3KYF/xw+7VdKh965LqGcIskRiG/BuJFhrwSyu6SmBsrCz4GXE/6TrpzWUpfCgKo3FNdohePDeGDAhAVoWQDLWHfa0MLywd2W+ZtDLgPWi0/GwOCyGzv1LgwG3gWK+zbdrwbKcnifVcQSPpc02xX1eu95/BqXthncO6TbiZFilT6GkQDFGFRHYfFSTjm7XcDEpoqUS2AkEPP11gLIiCVUq5BPWQKkXBNlvETxnczzJ5g7TXk6PVUs2RzM3WCroiq0gbj+dBYHB99qrKv68hVjG4rnDcaP/aRDLPOG3qN3rwV8rWnJGsOsplq7Rq2CKgMXFE0GuCM59Ppir+q8FoqhU6JuYsqDrbopqK81LmeofUq6XaF3HUlPitJ/AN3v0pj/B3p7mOb9gYk4y/111vjcvuGMX3Tv8F1/fzsGFjoormfsm5tsbFOwtYYhyvIID+ByGJ6gcXn4Kz6BF1w1pSHqRW5P6VawwbZPiGxEo1XEdYviREXvm87TSNaJaG7Lt/9QlNi/jxfeTJXMYTxNC7dEvYABUN7xUzgN2KwjegTaxso7CDjh1nDL6FKqKYe8o+5uqvvneecc81RiTqM48xnYtSOqu1GEwmLC/l0JHBdQEcfoQOGkS1CQUARrwUphE+U/OoW/OeiR3rQ4Uo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson
