---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgCws3FfU8Cq3uFPOFj5EU7lXxqvpFYbDXtnKfWdGcs2Lexro81KubzFYaHcJLbGpaufJzH6C2s7HGTuLHTIQYX6GPsFlP4AdswgtO5FcoV9FkZAeyoVVgbscEiT08HEZ0HcKFWlrDcTLx+MLZHGTlyvnH1MhvsRvlLllpcO3or37Lrg7Vpxyh94T9zvPzMaQ+xmg081RD7CzAU6nSYg9xeP7NkkkSXRSVqjr3yyK8GBrYR0jKwHESN2vbhsExFsiTOGxJCkhM/oyd1mG/auyPLk1CJfIKIOivvtYR10Dtmtu48bR4AeSOfZjIwKtkGGia3yJvApoHTEVSKlIP6h6vSKLSM0KJE+T9n288SEDab8wKNa3H995IDVfQHFEHxR99nGCULZt6N+aS4MJUiT3L6lvLH0aZqyqFE+F8muZj6uiGX0Y869NFccwo3PgROm5j9wlv4rnbMqylhCGaOAEbLglrhTOvjw0DCkeidR0Sw8SeC8opHwqQKMA1bhkQ0ryVXCyrzrZ2UGS+wMVzqN8WJoVMbhsw3dOWwV/8reTpIlY9a+zyHl/Pcyyd9vJSzRAYXBSWSHvCmIeUv9/zDhwRtw6QsqyYDP4uNei8ZC+FKAAhXvJYPb9UBcPXS03dwoWDwitF78QiOLZzaC7+TX7lzOHmA1SGmchJm2xoFwy7Gj6i8Qfs+frb1X2AwK8v7KUE7h25cCIDlNI9DFqsk9+VLmJJGGQCbVSd1t4wInJDDF3LZ6vgNH5psf2a1vuXuIDjotUcVf5VNR8tW4BeyEIAuDiFQdV77fKWYt6Ur+J0Qkwb8ms79YMIibOHz7tjg4S5LeX/IYbV5nl1eEIxRqzVehAJ2VQkSx0nYFd+G6JpyljVKIHgDeAmsfqAiSEllsqFpWOnWfsTkTBGklsqJHwtmMsx6nd2Ysz3NvksTnv8jHVc4S/KTo7DlvpIqDUANx0z/99e7IujDC4zTWZyRn4b8DoTTWwffQyd+ly8Thh0yMSLQFalaVl+s=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson
