---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAWFXip1t5JfyWTAgvy9DsGvNJsY+3C8C2mXhgl8mL2ja3AngVGyR71ZjxhYhzIXHzefXYiBl6yfdtMv3x4l6ix6IytDjeXPgpYn0tL2wK4NGr3J4Iz9I6+jq6k0P0UV8m9BW08nMZD3u0CEYifAQzZutjVMQZISbmC6Lc8HAA1cgL15dT2wM3vVDqGzpcu6dikMBfbrKE23nVRfwaiyuBUT+a3oWztmthRnz31LEpFMnUlC7xShQmwuOd4r5iiScLrk5QBO12O0loZe8Ae6EEU2Mu2zZ4CJuKjE1+m2gnklcseFeAY41p8WZh0Jr+g08iXSIv6hy0Azw3JluCoXHkn49EOR4/5v6CV1ylX3Y6/m6VwVFYICX02cYQcNFEP51blPFpj5qEPL1fIvT8yedvI82ydfyBrA5SK8i+jOfSYBXX9gtSleMlhvYx6TXFaiq5iIL4/NFB5Eot9u0cC5dQdHGsmqvRsXxe6VY6PF4brkiAN1OzBMSIPShyUNSiN4wt369lHBKUsEq0yRlTgwjyQUufgwwKg/G3enPXmHnXypwNrNJHnSVqjEpPNSLk8E5sq7PvhaHsW0b8g6Mq7d23NtgSHKsO6XD8CuKP0/vOAVpvQfex8gcau2+u34CUI0hxAclBEUMq/W5qw1Mlrizv1XdI9Zvnwe5EbXL/bqrnsMR8aRHa/90llrLVZw0gUD/mvcFvqmEErHLOVivU9IWN9BEQAu6YEJZqknX9n9ShHY/iXrv5T7Chd+QSQ6zjkjiJtpvUjKU96fZns1kqu9oe2Qb5JLJOYRzSEO3h2VhshPEcUgg+a8a8AvUK2Nuow+WTfR53Kdo20Ncqyrq7QdtGGKqthmoCyigeZFB47kFmRC85L8nBDDHif185n9I3xCs3fUnJs48HUGhKu6n+G5zHQHvuyy/8q5qAw8ELEAxOyuJZJgD07XzloOxU5VIW/P1KCWQwUGUWbY8s8gRb+xETjfYMPzjoEwgXB4t9VPrt8T1W+OBLpVBc=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
