---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgDldEjr1m8K+AYT6a84xxT62useEgMl79RWhpwfgM4f9eIph8bB4orxFHzBxZ+gEkrQIiTAH2u93EfxbJqGZQ++dIlqOH6wUfxxnY082nBVzfiJfiuBTrjOVeJOFS3LTL8vSt5ZCBEdUU+oEGo5KzL5L4e+0S+x9WZEsHOgmmndR7Esn7RWLW+QsJldT34POLfNPx3NM+jJjubIWzFWDWOBtAW+2dsx1cuRNRGGqjj2OclBuDcqQdQk36Gpa8A5VvxDoCfD4F5pvEN2SMyoNd0GQPSA4rAk/ZnXHWKvbyEsHthHE9/LTlh4PAanxVaIGQd/CpV8EZE/36YFns25K3svJjQJdke3WJTxoLq6THZU2N+Vb6a6srz8w0+0qrhb/E9gW5UFQujQ1Z9sZhWiT04EewFPlxnD0iOHJwXhnSSvWs5g/PTdN6Py2LgIFWeX+Li3znq84nBTnioW5wEByVYwGpMLwimrFOmKmAsvAl1AggT7JagSD2EBhsvw4ajLlhnwEWPwega08fA9jczf5e7H+Dy/nspHJQiH0bUi6NPD+cm/HMarMxQQjlVgmGlWHf5EyyntY5DaRLO3IJjyOU6YfpjWRcWLWtm7kEQxB7rGWfGRcb+9WqIO1VbWMm4gHEO62vBHD5Yk17McL6iDS6MNZkrqBuNU2DZbvKw71++qD1t6EEYKBoZRApob6Doq+43Y5O0VooWNp27VhEF5+cuPdoFMuTUEYY3mfrS0K9elHA43bNsYxozsj8F/N5E3foZquFoKoOslnnN9+EgR1fqsXJwLI513CcjAO13BcGbxzfS+AA+Y9U6UHCF9vEDhvFNVhLtuRbfPnkRubrJie1lDeXjz22l8nn1XnMOPrgv8TkmAL6WJv94RYoz6dgq5IyRZkXL24S07xemy/ODBdaj73IgujjmNBkWsypIOWg4S+D1cr+BqkbzPg9IrRYIC1yCvX0gAnYeVLgYC2oNAshyGePZWIx3MDVuc1eT6eKJ84HAhLfaUPiI=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
