---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCCq8M/IywOs3d2Y4WjFKOz+4fjOOhpdPs09qYgfrtVlvSO0zcmKCaAe4yy7i3ZVWEtV+QMk7jHj1pLLIDIrxcxj7mjOtm0QwSsB2svrIY11gDxzu9TXlxBCsNEu0GY6XhrTQRb3ery3tdC9QB35ktom9NlA3zKx4ibyrbPoiDDpyhoQUXsEPgm0CaAkB67vy5Pr6LZjKZtdUPTCSSmJkW8Nr756sxcZtljdCxNh0kqBlGrNUI1K/qOADP6nBGrkvyaDMiiI/M7JaPRzEmEtFjtf9YPIbE6KMn+5CbTCt5uVMTh9tRaV+HkEXOXnXa6ZzykKZ0v72D3RReTElxzeNaGG0tLcgMvPl4C7rC8ssstPYoWTlrKul1ObTUerSbbxdqeMGsKNmHzicJwN9QRJ9CmrOWENvlbS1QYlt06O6JkmdRJ8g9lkj37BBGnWg6zlXX2OLbG2JWZjCRs2usqx1a4+wjWeEPgi5CaJ/SQqlYCXtWn658fAZ00E1D2zf4b4HkOkYWHcCnygRjZjHtn7lI1+SQNzy5C2knfnHwe3/9g0BgypmqKc98U6Mg9qPf9yBMjEnrjanTGmv4Gx78ztfw2gZeEsd74gD1S24L6eaJQcEL0AAY7P+aFPU23BaIIg03LPe7OqvOOwawGgasNX9euunFL3l+8pCEhXXIkraNyWjdMyHnh1r3Kd3UHP24hNjQiQJCLhfhP3F+vC53AFQzkhEuhg+8mM4D5JF025zyfNHuJIIzqyfeiLByM7b9PoO6Xj/dDXOPK+gqyEyEMbkdvh6mIcNcFMMyu46rkPvRDKmM=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
