---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBzpxi2dA95t49TzF3HoUGOnnP6EmPVDmLBj3U8OLf8UAWSVaL/PCu1XIXT5BehplRLlDW2neBDlIyCtuW/jyCbhZYDn8eJVl2lWNLGhctChLa7Q8RFo432QlvLF8HRaalW0k7E80bKe+dv/ZXrqrhkOTHObBVfzn0M5zGDrMEpoif1I5uuQgwtIkuZ2IeQzibqzHGwwBD+wjIy5xOCenRsxUMkuZG0trtlC7j/9BBpA3zR1FtbdmaJl4jxLP3whttnXow3GjKJLeHWfVES9KmtYKDXOq2aod4E2Q+ndlx1DkIIi9OT8uatVaEx7LBzN8kLhl5vYuFdPiMrfSup36LUHPx3lcHmGga08CMh3qMZZ92g0cHECCCrFowkK571Ea/RY9G3ds6/wFvg6jmF1AGxTswsiZUBXVsGvDYAuP6z3+B/J9kJmIjJ1mhOzX6lPw8jBwYBv/eJnDjKh98T9gj15tZN1GdrftDfBQiUvIUDKrV75BOOMRf9RPAvYwhpSjEfmRYMZ7c4pJTfXynWuNWZa+Vsxeaisq1lrh6Cd0aI3q2DKUI48PYfwzR4iYWZ81xCJjHRYnMqI4DoBcMiuS6sU0WJIjxO18LeN/33jYEQnAi8iCqJFxmR532oOItEBz79BoFdoRBPmOq12525AJhPulL42JbWZZqHRZof+El1BQau4vdenjdhRO0esbqGOK61ILMRcAXVxZUttrWWlOsoIMZiC9R+HCqrf91gxGybVnCMb8Xr56IhckooGj1OYQ9vmpBgeO9N+7rv7kEUZm2PUEt9RYbXgK6kOeHMYADsogw=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
