---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCehiJDzAHwpROnbHi+tHFRoPsMYMywnTpwGcdFGfvU/vOUaOLm0B7ogwtpj/JKQzxRiYSWe5ZMdfqDeOfcY/W6yYsN3Od0dC62MV8ukRmIRJKonnzh7LI03Vpj3jTArlwtBAnN31d/rFy7kYFGkbVzYkKpEm+eIQxUijN9F3dxNeKzS+lxIoekaDqxt/tHRcd27cCuJreV/dymSHrjf8+SZCqPHyQKZNlivJjCNkxslknG7wdTcQziw0ytrwGXakp7QFE619m+csM5H+UKny+e/2m59+AL0trBVxEYReqyxc/xiakPbrectQPNETd8nF5ZfAjSSBW6hwjJaSo/t10K1aZ5NWcZclk7woAYw0nyagvchjysTXM4Vz//yVEd2MHZF+7JnluNp8IpWaYWOT+c6VbPWXR7vpOkJlg9Z+ZHoanJyxjsqbAr1TXf41MqsevIPA3Q8c7ytSvxuEtFE/PmdPkgxhFq6TgT2Zd4RONDYhXSd8tDckHcfRf/XTXKMOpcttPZOCCChl5xGUpco1EL1nWTMDtJWCuxmuwMwzUm7CO4GjF0qV6K79fsY4AZCOpg0Ixkt4zak6uezJlM5CVSkoAjlxVRK/Bs9lwggiK1sadmpkkkvTaX4uKJFSTNuTplvwv/Lpb3SFuOn4oQR7x6UpK33CV0/ochASSMxFxS6NgQWkcWLelGDB+ededAVbebbJclK4i7lj2C0Eb4DLUgoUTQOmphYyfYPnikp1k0OV1OuY+apawo
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
