---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgB9hQ/uDMviNxwSCUQUZCGho/cFLa05dTh+0ugFIQphoEkoCkwb0Wen7ckfciK2c7aErtYIx0feanW5Eti+8mf8XCHA5UnSLi44Qqws29nN7l3CwuMtmTAUJFXZfFvdqVkcWoZNuuYP7eGbb6DlEm8Y9/i4Nv0nhSmukNOsXliE25SPCgnmbUcr+/5uT9EFU12JHxnrtDXTKCyTAwxBBnLsJedkZYhr0kVT868ofUZg+YFd0LS8s1qy4ZVCVESSpuLiMgjIBeW5BPI27lzZCzyujkLg22hEUbsZr/v1us2Grr+iffY36aeLJqht+gbNBZi8ywIyLgVbBZZ5Cflpk+7rz6o7M3Rq0Fh8qeAa6nKFpI+VI2Zqg2P+YErE6Vtk2i7cJCfEXZwjL3pRNArNEqZ2WvhPo4BI8FAqaVakIOTJwyBJociTJfPDcZ4y79zwBbbo+XWMDyPUmA9vd/33P5mNRnnzeCADL4aNdFeJeKHkJ0kuxYywfLqE0aoewf5CotTmrbjXuymEEk4AORXP/F2qj0stmTKI/zFt1qnRnCeSRYTw5LwFrWOR6YyXXcAue9qfL66pq676ab/8rYf4MU9eC6mKBi9l8wLlAO6qZW5nhC0C6XpYVYXO7yf0/bCTRitFQDYNYasTOKNSeMXqgT67SdeOQzylhxRT3Eb7BvfFzbaJXDR5T/8p+hB/M7OyN25gj2stIC3pe6zsikM9BWoUoGPkoSx3/XGIZKNUIEUznVq69l1AXJrn
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
