---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgC/y9CImOg3DC9WBF1YIFjRZzl+kl1UiivQyc6kKBxdPTepmPOmUiXSBBZvT/0zy0j7vG5GOtHJkd3DyHojyRr6WNSwR9zEJ0/EXLR3wdaQd6S9hSRQBGPPy/zchihf7/7sv0XqUhzw2nqk1gCC50SAekK+A8Y2JHKujqZaYYJR6oYerKaoTLPyOwIq+ncfgAwpMbnc62nhtmNr8ESu7PIp3dJDVmsW/4mY8UGd9NhvQJU/EMmb8NDkv5Z+Oxm1b0RO1ZllDlnrmG7LCWcFoFv0DaNg9C7tp+Ra01Qt/E1ohO+Mu4sZa03hWp3+D5PQgn7g/Fvokw4i1DTLdBdo8VPnn2Mn6wyXw0iFi+K9iWBiu+tzD2PmUZ/fbm4cH9ZDp5cCXSwhtMnY1hHZJh3PQs4tP5TGR1kG8F2BKcPKztFueDPSKcUKBBQ+06Rr9d8aluK9p/ZtvdWnvyoVj1rwpBnztEgNx6dfNWN1eK7MjYS21TqefISyfFWoSNc6Qk1y1H39leDNp+TD0cSwPnakUoEtfe0Rzu3rz4LV7HORdSVPQFew6AHqnncxaGrbnb6wCV0/xkL3JNswGIQsx+quN/eqRDWh8PLuazabHb1TrTYgneoxwaOktmb8B5bixQjTrCUpmlVKC/OFtG3gT349WYZCfidjjmNsmOjQJpNcKJ1NwMiroB7rwQCbTc7Iyp8HkWgfDcQZXLkHFGwCJtDC5kStrF+A45STAc29pRCYZ0GfNCz6BBj8IkEHeyIx2J8NugMy/9FgH31x0GS2ra1r1QbmOL0oR4t3W0mr55DoliJ8xld/jhRYDhohxYd75J8+UTwTmBM5imhxyWJZxB3TXKLcGdPq97SEf8bQtTL1uQJ/Ud3TMs0RWPBMqZbjhDUBanhVa4EbAHJBBEIqQZaOOUf2G9WYu836WQBVIdEKgMgCRn3BB3GmetApocNGASIZ5SG7xw2bmqtnidin9afj5l3VX5CtnEhf6hA2xzackrfG2KAOmNOy1Vw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
