---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: kube-system
spec:
  encryptedData:
    .dockerconfigjson: AgAEIug4X7pU7V02E9ZQr8UbloGpXSGwkgMr+y+7C1luJf165ZJgi3+79fesAOL+TCkGGLwyDi54XsyMqS5BG4E+ygy50GFiAKN2JTSdFCcQqdzGEIiIxaxyvfKF2VGB5PcBbQDIqpRsyB4tSFauab/pE667cy5GUeVbHB50BdBDatPRr/2UnKPIlg0jS4Pqlg0QET+mRerkwjLfTrfJGa3S5ICoMvH00jSZNugz4hvBc+CJQanpgmA7hIyrQY49jq86RIVuGRUP2pQQY/09B/U0VJpOTx5PxLfw/jsOrlydAwY9GPyb6bCBE5Hc5IhFUejlTV/uKGHOxXsmO5efkmVkix77jc4sieGTTU7QZKqByTNMUBMjo7q6dQ9i1dIvqGSGJQ+TOXmXbluKocUBpRZULW/fTSEDeV9rqIw3IVzmdXKp2ocycpwaz1plRxQszh6MH6EwjvuvxX66j/FwG/mt8RyKcR05Y2JRzGehpv954yxgm5ePrpNyiysWu7wNHbjSu7jbjsWKkdlRTKwW3lzSBXtFFDBgqd+AJeGJab6dENG17mg5DKiB7M9KsgBg3/g5PhGOe5/Ro8jKzYQ9wEBuDlT7GDZHRAy/VoHiR3938gW+tGHDnUFTSJq2dzUABaBgWpdYtAraMNtcAeIRte95b+iEHv86Mro0U0ZlAQ3wSDrp2ZYhS+G5BBV/hjJYrogDDHW+1afTStSCHxB31onoCSF0zw30aPqHHg+zXJKMLyZknXxRFj91d7W6UZ+88ivX5XPIJ4rMZ0WHPTHgbUNiK9tD9bI7RU7vbqoPM4Pllh0nDD3bbZTOtjZvC83LMFx4WFJRcMb3MavRbrvF+yuVkW2mNnDj+xVNMCbBFVe16gnaWxr/hdM4mp2HFm7ivDpdUySJT8NsVH7g5BwAvdrhtOnnTS1X7SWFxCxxstiENlvy6CoVI55sh7uTn3KWQ7ctyS6UNHZs4XCXBfJlDAvCu90cXeG9JsAOOvaDejdEuCD9MEgER2Y=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: kube-system
    type: kubernetes.io/dockerconfigjson
