---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBNoW91yM5LVq6s4f02GqfDYD/CpbiBlgDXodZvMeW9Y7Ahdf2y2NiKUT42jEUTe4XDhvzqc41kh0aocKC9Y8wV/MvzDPfKeyENcByZQFo5UsOFNzvXHQ5QfYoEK9CQiRlrYi/qLh+67fVF09Ozc37+dpT5whhU6iKuDNb+CUp4Oqx3Wc+eAMNZJN8lymPe1TiOvQgBoVzKL7hDErCbDvRQZrjBF8QBiwD5iFYm7XxyW8oesrBbUDNWTLl9bUE4Z7Yn+lsmYujgRo91k45ziWgoVOtFsmyQyZ3WWmWdFHzbI5VkP+AUXaXIcJNHg0BNHr/bWLkJ11d0SaSGIySawHvPD+yQAN+sSfpkRLWjym0ifB5+ovjJMnMFYVLI/ukehOX5vXEm3OtlMLOx6+echRI2fe2G2p5bLINEc5/tkdL9QMoFo0Arwf7whyh4bxz/jVwGshvxXdWicZ523YrMmJz2QP0ER9nhMU8oMbVodw33Ui030rjkQSjSDTjpY8qwJp5EAg5iYwN87jpGtL0fNDqXEY9NT2kOxDNdzBTJzn2/cjL+HijSZxDoSnCbtXTJkG5joAZQQPQT6H9CKNUK9hwUN7wLqbc2f02yYw57Zy/c9+5Gz9zvetnUD5wKMOvxvnQR24fFdsdf3+McmGY7khgxsEMmmDtXeII4gFgm48Tma9gN1zQPS59IKbNMHD/rb5b/t4EXkEuCjUzw3EWGCLM1JKrac4jyPXHKcmL2fT0HMc6mQ127RMlPhe50idkatnfPtJvZK2UGupeBEy4eVpu1E/Awvk7eicgkW4Zxelpflqc=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
