---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBH8CBOMO2tilrkSnB9gFlIXsSniBJMovAuKsQlYE2I29uNJazVu761lEWqK/QgKvbBpooUvdbC2LwsHOY2AdUTAhYY4bQRqTRwz9Tkfz5BfhtF5Qtcs5d5d2jMurompP4qxJP9m++yDlQec7dLW+D/x9FezI/VaO5z6enM6NjbAfC+k4kKRRULdb515nJlVF6b2y6hpPv6o+unRmBj4Ax8hWBmCNcqZe1dzcyLGAHRud6bon66+n4Z7eulRc8CT1FPl8YZkQp8Xe23/D6Nr90Emc5x0xZHB3vyTg4AWkPxMX8GEsd9FakP7IaeQCORUwkiDLp1+js4Mrv6Nr73V+mgO6bZq+I3YHFo7WMqk0zYo9qW4CdexWinJZ52otfBnXQv0ANHz2xxq3JCo5HIk4WCYKSRJC7ig5yFwgD1QctqqZFq3Vl6PzfYh6g3DmeMYLjOr+TF5cdxTLYU0nL6lzYyshlQN1E4++mWkRWCjyS8nC3OfnrPg3gykOBrDmJRerVWaiPE6L0p8g9r6B4Ad9aclRnTFQtepMd2PK9bnF3Jf0f8lnEe31huXvY6am+Shv7jlnp0cVntYyYurTIYtZaE5Bdr1mlT/LQ+qqjxsXKn7z3KnDm1L5zEjgmUWWqIMbfbUYs6/P4WMhC3j7N6/qCGwiaFdtveY0XDnoihixDvBQEo2E35GRz/uKwm0Y5hSaIESffxwl/BFP83tLES6VT63c8eQrHJii1qWi+Mp0bJJ4q1wE17MlVr
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
