---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-auth-secret
  namespace: flux-system
spec:
  encryptedData:
    password: AgAVk93p8AXEy56RIpr6/y34PVdT5wWhyDGfwhRH30Gp5/Hgep77Qn1Y+QmopyiyctIfCVSRrqX7ecDnofZDYYDW8YI8AhDNb4tS/tsDGCqRsCpqmfFIr21DxS+LAuygj30K6N/MfALmCm4N9tjamWE296UXRCKp2cK8PIPHUKVq9DjletkNmLpeS/wNJedhS8NSMD4HIp9VcvUgUalKgl307W/5eQVfPqQ7cK0ejZ4yQTtbmwJpHJVeXo0QjabKZTCn0aUpMfusw+YQ9TzpOmBlRyfuIj4mwGk0nxF/lu2+eu6ksw8c/lHKaXUkereX4SK1NVHjBXuSJ5X3mOobTdlqPHvugVrefxeoo4BynOvYcFlRlme0RqT4fEUozEB+dRmLEVtzSaPZ4jHRHDOmHbxemyW9rf171cYts/DIvORfcknYrxJIayym+AbI7ds+64lQeDB6UIYNWNibr4FLw7w6TV8PZVxgYXdfd3LCpMxDv6N18gAXxW6Eh1oFjclVVSCN3KErOVGUHBlpeDsR0mKYluhrn4lkWRDFW0tbgRxAo0GaG2XTMlb6/NvdqIe11Kuj34T49JkLB9bjeBYH5wBvK6/e/uf0HtN1Lv8VikTm0B9TwewEKnpNq/AvzCuHA9mOUo1IF6ZRbZQ6dycB5JAyHruFL2XTiddPy0w4v3egixgvjV1YJ0zpZtUCECRh35wHOwnuW/nMNEKpnVdnRPcJldal4TLwDrMjiHHUWEHvgptu0fOagyFP
    username: AgBkw8ebbxoUZIAR8GZuJRmbqAZ1hikpgmFLgqiSLlKfSx1WlJPeyXKN2zJwDLbpOqRz87X6h0s804dcdfRCmptHFxKBrY2ens1onPSdrGu3nXpVCKhU7+I8nrizlzoZ1CyM8ttvYIpc04x/JXSEVf+CWkRQZE8Gf62nGBqO165hO6FAhnuBBTC+b5PxxRRWcOuI0JDhCCqtE79RlM20ki4xv+kUrZD/5kc8282sKujFKDFRhWKB6vLiyFs/KrefS6WaF5fQOmVr0A/xg2FyYpJSZfb6uSEmyoIRWYUJWeRs2HaWUVuKBPcR6Ms7+f5xK42dwZVdKC3fC0WpaG/GmPkvkGdLoHbtFlz4zJ9w3UbGJ6jKj0vLIjODM4Qq9JpnwzQ0K01CASyFOnaDTpWm1zt/HYN47/V/Hwnem+Euejp0nG8NNh8nXO6Jcx4qyGx14RJ/22Jp9B60uh1y0vZCPDTiO7NhEtNhww9FwRHPsDJuWzBA5PxHAtwGmqmTgYknorcxG/f7gBMPbHXr/GoQzpq0E+yJiKGJhpy9BmG+3Fvon9bUu2M9+wNuFLwoFdluK/MHLyl+eoKs0hrkwyJtlrVGPCIC65647mRdsTjfs59aM/Z3GkdND8fmnvPVg459RfNgnoIAmIzTgP3Na9vnFYj8IwlLG77CKkE7mvvypxZyeopj+25nANONffIx8gGiIKFRtNg=
  template:
    metadata:
      creationTimestamp: null
      name: github-auth-secret
      namespace: flux-system
    type: Opaque
