---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: machines-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgAlNjkYooBGzDgr0mXyhf+Ytaw5ZA4tHaL1C0qr62MB9PmfZVc914JwW5lkuP6Xnd6TVWrTTtf7O+OK9p+fcZiKsiGha1zr8uFNCmP60FvtywU7uAd6Ko5m4uTK3psYDPNWTpTMKBn6GU8HvgEK6ekCnV9thkLYO3yeo5eIV2xb4/KJx5G7QnvjQHns30yee3H01vgYNg1vdUh5GfKttNK6f6f6T4Lcj/nGMDOOYFrG33Uz9IxORNNtzlPtxbwDmlmI+gP45AlZ+EwrxdxsXlr5m+4/Xmk/5pDU/17AP1LReI9exyVqRGvR40jAfRaAYZ92MFWGJeXMBeJZMOjyiADiRbuhUIRn78umZ13BC7k3DQc6X58T+Dv3sNVOZbyoE2wspBvguHeWuaNqmWPTcLdwHszx64w9iRHNZVPGSOufY+qSzdEr15PdpofQz3kfPaYTpTSkolOCDt7kpu4jSdMJ8CrqmG8Dtir92dZd3JLQkfdANphWWGgHEC7r8Wc4ZqZXoxfMeNhiJ/F8iPer8GcFPTVuMYpFvcwgddoIGq48Tha4/QrLo1NSsgFnp7rbyTwsNN9VaHPfeT4WZjR2S8hjOWVkXbxQXGCUCOYgDocTktjXH3NDvfisOEvQlLE6oJ2gvfq+JwfD2R6EIHlnxdVCHtVDf3CVWG3b6KWGilRCUShTsw9v1shCsqcPzwGadftHa2Z9dbpevuMKWO4e68fbs5BqIuuQHt4=
  template:
    metadata:
      creationTimestamp: null
      name: machines-db-credentials
      namespace: services
