---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: migrator-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgBwOgUbii4no4ipEIZHhY8nBHBBZexgg9ElzW2DyoF7Cp9V50cVgOyeHwUONkM2MTTemo1G/NVz/Hw8yTsMJmSPXKQOa1uIm75fAvVFKpXEIJehw9/4QonbPkvBsbVCjQKTGpp6vgdL2sCHx4nR+UhA3APOb/AQ68/fBQMlJgKoCVLGF+v/YOE9tEpEph3FNj8ysA8na+nKqs1GnH9aTutWBHhg+K7jzfJFMmpMigBu/n1Hj3yhPAO/IGvkgr/j1T38hC6Jq502hE+nDeYO+cXFA5tYX5XZOMkxy4xkB4Jq2LRxfR8la3jdRL6EXQRznoj/cA84O/YlKLHnrJL9MuqzlhuaQgRRquFmMNfCZZh/BHm0eNlbWU75zY70G2F7mM3MWA1e4Ns3TKSHqJinb5blIP2QdP4EQHoYBpWjHCdhJhYUsP5l2XXbfwC7sfto/x4utVZpE8M7olGIYU17qdy3a93RGwh4RuQ/JC2HHhd7xrDqMLXledQ3+G2a4+5TaUpbflaXRb19Wwn3P6iZ64lvnv32HIInNJlsWgXjiODgdZOLmo+GLuQIpKQXCYFVJojx56yljFPBmc0PE+PxU42N4Ms1Jd1adtik4Cl7oRK7qGaT+sq3Hzbb/mthStnnDaMB18vaFDezQIA2oKbARXZuuOnwcWrHspjmawEGaCBk/mI5UzjmLMQeL+ZeiZnUPNgeqgOkZLaYlFRCJqgvG3dh/FWXt/lfonc=
  template:
    metadata:
      creationTimestamp: null
      name: migrator-db-credentials
      namespace: services
