---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgBwAgwkybjrSZfTtpfUZPfOV8gb3OfWJw3aB80bIFGYCjmLxjzYhknjsUenT93sGekbUX9X7kS5DBgI0T9C7X4QyR/Igy78v+YfVj4wTvARszCSCJEhfvXehi9Ef7RbWakye/B1EjsYvWRNHHgPZL0YTbgXT9Sm58r8aWdAiLP7Gbb/EknaY8eRbrAltbJ12pbsC72Z2XQF7uK53DVloZKCBj6rd6VF4PS9OHtXjSspkiYw1C27oIaVuwBo1R51/I8teAbbIPpv67yrSgzQRGx2sxEXByRaqeIZWhjdC9Awv8TBlTPvjTg3le9/9ULU7eVLad7cbIhU6Dzzl10wkVqa/8lkxzuDoRuN4gBhCYuVr6orXm2sLC+r1lerjftfEXljtGO/CBJXcYqxJCZ7AC8SFnavOoL9cZCxws6tJwzUKbNgwjsrWen1wDZAKMyUhWmmQB+NTJAoIG5U6TdWWU7+SI52WkzKY17Vyprj/uqrjXgQ9ZsMTGcA+bPBc/wGYOSc1dgl8PqaFxjZLY3X8XKqzZlt4/Em1EfjPaQ57j+XpHDAdAmkWv7IvI6eqPcVyQTwu4EwizqJibyXVXalsqBH2c821raLsQEHJWySomZBDoTjdm1MrZ1Wupj2eaEYr1Lw3tKocwxS3RNXXoJgLxuQALCtCRkO+Mq6MRtLt7Njk2n4Leit28gbFPgfBItd3FuoGRAylUJpZsea5n8omrDX+nbGy+u7Gog=
  template:
    metadata:
      creationTimestamp: null
      name: platform-db-credentials
      namespace: services
