---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgCByrc3uktEORorauC5NLPv0a3B6brPSIdQ9k67nYIiYS/ixYfDXGlMLKRKIJp+K/VK9S9BZpgZnqN6M0PAKqT8HDkYBcU4nwFjT3WfWCnyMPLi53+GHMF1tgawd52qOnLq+qU2ErRVu04TeWS5b2CyA6rNoUvswmldoK3cus0naginBPo8mw+1NinWtJQrXkY57SaUexvkT4TO6jcl9ID7rzRPp9OwGFm8lT1iBYAS67O7mP/ePG7XAu5Dbg4nuvxq8FLzTpbHz3BDOETI+A+d3bFpWc28NPlGOj1wbLWzxyi1/AjX+d62WGM51WF4KIgHlU0uCbL7rx3DSKxY+d2o0/Eg5PaPXLLGALPxKYhxFDtJFAFNKcNPJGyY513hfW9yiW/2BsEuMdGJugUIkXmTj7Tq0IexQFWnQUoU3xF4uwTWfpJ5SwRVAbA78znt6zYMz5u2LBFNBq+cNuRTGW4a8jyfatBFLmcYMmRUoCEmd3vQ8hnHrxa1glj6qrV10BabCmS+AW94DNquok2IiagZk9/k3e5Xgn/HtX2kaFBWnIYpSSDAUzEfF6JnR7nMuP80wyBc+wMHCZR49kj1Dx6kbzXdK2wPZU3pfIENpqczFUjdyp7LvEx2QN+CTakW4z6JFtrQYGxD6KZDzYRFeh7/4E/tkOwtFbfdAWaQ2ktMykf5axw1VhB7vMFVdL5NDoOPRasYFLjhRDMm/xl7wq+8LM3HyBGTHy6puJzlvMSHcap5S4OvQGU+tDjIDu6YozZOA0ybHRbpWiRBMq2Iw/s+EaA3MqhVLE/mTassJEp6ontEzCXvHtpqKVvyywf1qJw7wgoyBw/Q3gku5Lk2mzX0OuJDWKwjuxHHokdjOeUza5PWvxRcav62MJx7eMd11XdItVf+kaP0gWUV0MAexMxeTlNNvguBBWHpIVNdr3yNMtUPya7zT5P5dxHh3ipzYBpG11vpO8AmXF00wxf/D2UnjlYraHr3ySU/HAbmPuI2WnrQ5hl8KW0=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
