---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBP9s4o7vQqZBnSm19wIOKMvocMU9T5ZlfueoUxjTivf09iIMtTFlcilhp2uD2p52SrKeNTlW8nztPrq05921tCeUxshKjy4rYxHdysAp3ATXYMQ7B+KkZwJsCzy15jObZSAMjF/k9tHQIhjFncTUlex7ZhdkSfZEDdSIN2DFQn7zVgBvsebc594z8qwB+w53Lv72yErJbCWh0AmFJASYpVHHQ4pNl4uDJsxbK74Pm7e+QA2G9tAqx78uiUez5wp9el1n7GfiPlgML7Y8GrkV9F+SyF5Y24GyaNR72xy4mRU3axY2riAWC9aTUtFFMKL0dDz7xfRQec7AgTqDBEu92XPP4h6glRzd6M0GERKyO4+KnTmnU4GxTJ7aKn/B9YnYh1fXbPcdjAKUBTNaF6NK3sxpuqBOnwLS+2tDkZpZwMSUfqLEmS+kFeZt3cx0q+hY0YmwaP1R/JAxqoxVmi0w3j3iur5pa+kRtrLeIKZJrPPgqe5sbam5cQpSbqrxMzx8OH3XMkABJ92MiuPRjqsbsogI6e1OhU9A6LEd2CiPoBg4Yrdxug1dALhEg/Aead22xe/VonsVcAZFL+cWC4v4IKihhaErKjvz3R1D+1cLT5vukZmRmoeqx3cPwsdLsHMrzZt/9eeeFH7ap6x8AYaAE7ZT5UiMJVrsKouVshIuh9uRkysQh1c63e6zSHKuR/X31+aS5SUyeUFpqdx3Bi3DM32gGJBjtpVpvHci3P+wF3N4RlcuePga4fYmKeKTz5ip7gALw1y8X3ptyLnZ32qvW047WeV4Aei8XYWKYLcjo1dy8O9OOQq/X4/HOsrO4FKo+ae0GiHrgpdc62mGYk0fioS3BZwuod3/xQUECccVKg1h3sLk9GBFS1xqmaFtaPFFE9I7Kd6ubXPxmIZONdVEFwGJG7Kk15stAI7/mR9zg4iew4Re4zjTC1STBrL2aW5TzLH4dagG1OoBhARw1dDaUw8BbZSjN5YMfqmCyU9kVFUVnghX+xkxE=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
