---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgB/oXGej4BFgTxifZIC4Hvi9yLxITGtt9s56U+4IAYXhkzOZIUQgqxmukzs9tNPLVqC93nvLmH8OjUl0Y+ZBEYRHAH/zZ8NHGsSL4L5c+KFTVmOKqJZlvNEfih5L8xFZ6YKyZlnpjQOYLZPLLBBQB5snTF9jC/lCEDzKGELfP451jsVT5Uv7LCMotyaBrKhHkCFpY0nC4fMB738lgJeJcYsExODJPx94nGe66mBegrmTnG8uOs95wc12w7k5Cf+TlNvfXbQuhxwpVOSlaV2IgQd7jibC+Gm1Kh3qM06Gk+7L001ZvFQqopWht+sZvbzjtDYyJrC/ZZ42VaF3ZZT3XGJdowTax6BEaJgoD8GrIaJsPn9wX6rYWX8VoXfOvewVCOogURjivzWJRI3gmKG+0sl6RM8UIP86hLl3HUzOGjaB7D3l0hwpMJ1MrauBF0i3kPa5cI+HTnSwaSCYgyozO67FRaX2g1XpzHdQ+oCUarA679R5Q3MbUgvrMJgPXe7lzt+/NTcUQOWhWov6GjO4KH1jEKA73oyGja5gUegzWPQvnxF8Izdod+GQ27bmSKgnwYVv28sc72r5/01kuki//sSMOFFfk6gMCN8aAt0NpYn8RX1am7kY5ZkFq8SO54UnsUZnrxQBSy8l/9YlpWJr4I44ek2pNFATcgIF9W3H+VxarFSAVkrDMu82TSFjItqts+YdqpNi86lUvp0gKicozhVchpogKXRAKDh6J6fOiiLV5lzzFs9g2BqCglStX/vQDggyXgmHMc6wTIuU4TjtIPKAgm2rfI4AodsWYcWMnDNe2Q=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
