---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAuqMHPLKYRNvfJNL6cCIY3swuUc0ZBL3izPDY6K4njy6MmR4L75H3nmeY0S4jY7M34rsXKZ0/m+OBC/dUrZ5Jyr5YV10BZAp9NB3aE40u8WToqKuSzspSJDCmlFSDN7mKsP+RrUENGR7B5XyoLH4pgqrBpzn93KNQJ2hf9inCW58Dl7kME+SMtkuTTTSahkMdv23zkne+5qBj/Jo2JCjdrFzlWk3U7zyJa7xZImH43MuqZeR0yGFPNymRrF8/tJw1v1mwLiFyKX0knCCSMROMmkSYFNHaEJlgLssIoCwpiUI6h1dqIgNxP3tBHSpB/4GKgRzaneZHh6j0VTHQvIP/xaArnF5QknJMTSAhc3k/aLeW6YkYd5/xIFnNQnuvUpCMzUA/mC8SejsPYR3QWHl3zPSe0TYthTXR3s/uDDZjFFExpZTvYyocaZLJboFoZO6iVSPOyN4GVa5djWg1ar5rcYehvlsicUeBn5arHs0zKqkrCRmQVqXFoSwoS3bgpjTHimfIJ1l1+UT4j+oChUDN2BVbo3+3ZP8qYBfGtc943/BwdSPy+q4Nb+mDSGZtORMqgCtRs1XO8rzZGheCu444VERdGbvCIlPHwszGam7yDEMuu0hKRqIjJFaLgq9UJs6l+/hOOB2HwwTLOrAemtX8Kod0+nPbecibeBnmhQomwcAGxHP43rToeFZX9qI3u7R++b5jhldUuMo9Jp+CmgxSJ9nUnWzoDbFFLTq5p1g4v1Jwd2RQY1MN+Kzg72JxR0zuLXJyV9wgBrtRaVMd4HtOHLB/0gO3CEsknKgE2+nc7QJE=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
