---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCVgpgf7odjqn7UfAm5kwu6K56RL9Q+9P7KCjs/8MWOPGktWf/vAPmc4/f6aBnjoilEgipUbqu3Si7I0QnaalP0o7U7okAkjtDVKELzSMUoox0MyjcFk92YdLMiJccIro+KE7A03idn9MmUlBQtxifJ4MDU9x1Jm1KRJoFHGoK5/EB6avNzeC02T9kr51Frn8XZxU0dFnodQldjpkNqmTOPjBTvqJ8/FBtlPCXIHtztM+axttcFMwJOElu+MdD5eRA3Y4s771jin9GWsfn+nRjVwJjrG3VaJ6NUKuxE5iDeoDJFdOIaGh9SUbkD4xkK1LaWLRTfttXRE5j9lUBQbJ4rcV1cti4+gegBLsPNjS7vS08dgaFshSIYERv9HAYQOH8UuWHW/0g49QxFF8yrRCSHsvdFT0eJLbqacmyEdxWpediFmuCd7xFb1zhxfpOo5/j8kDVzGLr8Sb7C7FWf8jKnTdWncvnpSQXSQ4o7Nb3wZiSsmwxQvuZrcFeClk1j1BEA98nBah1pFSnJDFv84tQvOXdUr5tNckEq/DoPRfXlqDlGzWImMDmYhjc+YCKGWPm30/vLfy7Th/WLQI3AbDkp1WBU3aLnbAm4GBLa0XkaGHEQnHypc0yX0GkTSaHB3oMHkYbWJR+gCPC+L1O/+KqyxJL2Pb9Qxsvup8RLoOBdtxy9aa2hA/ds/oNyCfKUj349e58KB9kuPs9jg5aRPTnZ7Mz6chqdQ+JODxpph7zCMrJU5RCxNyRX
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
