---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: migrator-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgB9khM5HEScKBlQqxmaV31q1Af9rcd6tL5hYoK6KUg5v6Jd9jKkZnwihx3LeqXg/2+8XFPKSgEDNap/gUsYmwhpZax5ufvoON5VkqfzwaR2jKWyixWQiKccWnqvNDdun8rgphLjCNnSu395YpDGgQdz7ZbgCGsF7Y3OPmA1CRb+3bF2eSTZXiog8RKngduLMV4+nSmIYn/JilFN6HrpwAE88T+y/ArJ8zT7YT5nyHkYqXHohIt5lJlSc9gHYvgjDfjkoX1jmW4NwjPloZu5vPtN2vXEapx9lZ7bh3dJbkuU691p+HbqUDwCwNUFnsexnN4XmmuW6KoaOMlAKsuem00fQAgQsvEnfahIZYfnRXaOvoeo9zGCtGfE6uqotiWmjT5Pf2wPaghXN5W997DXojizNJ4uKTRVjijrF/33uXjz+q8fRCRhGciSnRb8kCi09sntvMVhq/yWqCoZrzBAfcEOODYNHoobHrblSLUhJ4qM3/cR19mqgK3cVONt2tZslR2/lHEIDlXt2x0/Sch1fLG7zt74yyqJPaOloGs20oWhK1xTEBkAgRx9BPs/fOqK6WYValUNIdDyiJbZ12q5oPxsYppnCLdv29WwlIY0br1kn5QjEnwcw31SdulW5KIlZUbwaSix+6vLn5h0iGeHCZPmr8d/FMiykx+hI5rTdRmKQmzTdm9URxGCFDgXTbGb034B1zSKbVkn5SmCVlYxQZNVwC/5rBXZ/L0=
  template:
    metadata:
      creationTimestamp: null
      name: migrator-db-credentials
      namespace: services
