---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgArkffmpxxAK30A+C3vQtwLUmqQIpua98W1Vh5DIB32mH57IrdUAQeckX26O4DP3XPDiRlQOSM2K04eaPJRzMWBhyTKf3YBuZWexpIbIRvjTwt/UlSB9tnqV9WaAssedG3OA7cJFz5xs/BaKEioCyqz+5suvxLJ2j1J1fWxWg/DRWsHydmwIeCpLYaukFDIFSnXnbL7p9ZFPEoyUVghLzviM9Ia0GZ1ZrKsO3BdnAqwoiFDSB+m/wwPXmtBJkfZE+Ese7EgeUwfkJFoNGmv77+cX8ONR2kmHaerMZyjg/8lEBYB0Eu+l0wwe5rtPK5kFrrC+/TjFr7UG0lrr8Kxr1vIatQZkHqcqXl/xsHqgBynLnGw6Gshy+gR+IAdvg6UhyFivWiVNasCLceMQ/C2X003I2RJClx85wW17N52hXMxpbtntnlVpT4C8WA1fX1vJJKnSenqZBsjSbYtdTDiV/N8i4u4bqfnxOrTAqD9gEarQ+ESnf47xe0cvD0YPgMgswPHNFDs12VK1eHjOpsJMfOUBkzSmkJ0gLhl86xL1nOrQJlSr8rP7lI5tSfkVteSDBONZBwNO3E7WWaCsGWCg/AKF+apcNC4RZ1CTjsd8ONAIuyZnrfSv5kzmEhSqW2aR6JOYZn5RNbGqpm0pac0uLVRfwojZns/AnO+PeaqGIHN/nu74PIgTh/Jb12jdhb0Bzmk6GmmRJzCuntfcVJvs2bAQEyVP5woltS0c9hnxg+amXuHvRNr0oCJW8Dc7CGCRMONWPrHxlLNmsmcoDV+Qc37ky/p6Eigq8CJIk8mhrlJ2udCO1LcTDGdQxjLqnYcsGn6/PIMmbF4NQrXqr3AfaMO0rWVKhZEVYpWRyxZ4hrlkzbBwTQHh8uMKnT5sBLeCIfS7vxy0vV5v89GR8w8oclLQjN73/iGeo4ihx6jhg+aXYXw3Hkw5SqlLxbuqXcu+ETT+LBz7XDxDoE/1bZRPOAz+uGK+PA5rpDdyxfh9EVhjfZIsurBaGU=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
