---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgDRZ9XiUz6bbiihf12mgkVnKAxWwRRW5QjGRpC5x3PhG88GqoV9ovetY/NbKNBMdBgWvnUPd3mcKj3ATPz4pNL7ACa0hJSFs/dQ7+lMSPfDW+eAudxFREdTJKNAT/sRBUtu20I07+zphi37bw1EwJBImxMP29/c5tWNdh4LjZFGwBNfNn02Kgk+17KzAtqs6a77V5F3oXg0yxMyn4x2WbOjXvpCNHKYkbnnQQb7NPvJH2XGi3C1ao18Zh9WVDpzoo5lsxAYwoxYx28AhGwi2LeYRO2aSVZtfFnINo88Lc+CAi0BGG2+EIa1A6/FSvp0d5Lbd84oQMzvY3A6AYfqbDEnpM8T6W/Ujx7Av6dCO/d1uEIs/uPVMZKc+gd7tZ+g22B0ZyLcAVRUVE3dXYVzb8ccQ1gHN3maEMhrIf6sDHivg6GToXu2GUL43QsmRnsT3OEWj8cLwImk3cjTt1WkIzZsgEdrXYKOffnYJYni08vtV4deCgflj5gvh9l/J4z2QwGOcjU5fuj15vGWGmTPBR++eOeP40cb3LJj4gDRbtyVcDWP4q0ZVYU0GkFR1xNhDo/Mdk/9X9o5clIhkut5ZYgCiCbt+WWL0Tn9dIcrpjOTAIuMeNsoiyiJNThkyecJYiFH4mS6o4gbg0patSThcylFyyQRZlMx9p6CTCjxbsg2DHBjSkMoymspSMWcIp9xg8nO8z1Gr5b+XvXjOC4BpcmzdGmVXarkYz3Z6o6LfcbrC4dZ8Rbk3EgTKRQJwjVASN1rMiYY1LJUuU0Gye6lIeT+UWG+FmlPFaiXrXurIDjREN5pox3bTOW7wVilIE/FoGdNK6VZeXqa6eBn6O/wbUPzzxW51na7WuMgSwnXCG5Kj98BYTw2e6qWqUTqBH+JMi72h42Vw2nUg5H5msuOKhWAs/JP7c8ddFUEJHCiLQjwxu6+jpH5oObajTMkbzjQAKn0aJzXgiuek+8HSItuP1JoTi+yBZYf/oe23kOy1Olcr/3SzZ1S8sY=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
