---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgBJQFCyFvm2fGJDb1KElClBUi+1dB4E84frham36VhFuR5dneZmGG9P5DHG064/WLJAaKdA9WQaV9sb65ej8voeyCobTWltTCehMmMDSeE0x7Rbxslm7VK7VHcu9tBMbrysC1dOd9xZv00nQ7UYGqcM/U3tqVD/YZ7YvDKralJ8HDi4y5gmaj/1SELdlwa+7T+2tXoRP1U1oM1nrOYXclelPOb6+3nG8hHztAQWKLLQ1sBkREi+e2TTa/H1HSWlSd4y0bDoWcSjDfNLFgjmlwV7wAX9k3gpBzSSbNGB1j7A6lAaRZBFuI1Za81O++r2G0D1WS/l+TdClIlRSjP4nAfELANcsVY9zzMiOEdDlGkBMTq4v5JBYl8dclyNpxxnO2GOXfqv7WQ6xSEIhwubti4GoFRRAO0jYBm/cMMwbQLdtutIngnKm9szi/zWFBBeoVPvAlVo4O1qypkKmjV/ykxi9Puy3gZuZyp3ZcfJh77RlcpKjQ6eKoENVuvesAbLHnH6BgYRTvMJvqy4h20yTh440xaTmfThau1BFkFKEpkxNx0ZbJeTtgZI+0feboSHz/n975F7ptHpS1VLaCGYlUp6IoYtV4sVhzk9KcDNtXKsvIWebpjZEZpT///CO4OsrfF5JBJXs5fxoEgWGtn0J6zDqQ5iHT81we4y1Frle3BitMQlEtpYynzFh0WJycAg5FdzfbQ7cj7pYSksmmUH7w2Ze1xh1RYQDIq3AoUXPuYfWvxTJ5B0vjbJaFlSx0PZgDrZVdJsEGU7C0EzPgcGcaKDi/kAcGUKoHK+TlYc6WwcmOxlkq6zUcv6PseUhIGoTqluXWFxUNsh8Rp4TxGlIbuzKIO8WFyI0zlCq8pyngbWhpsc0KLXJN0e4Z0mbTWiDYJ1GRIOxRozCjSwrTb6YZb1fhRAG/Hol+Yh0E2vSRWwvSU4r2cRzGActZqgvcY0X8tm3JPJISfaB8hK4z9QjD4glx4aYF8ZfbWtbUmNJaW9m/yg5I7LeAo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
