---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgAG6AIQdyOXwcv1Z8ucsiMzk8L2sPWOyDF8x8YKUo1WSO6fLm1pVg7DjEyn4h23IDgeIsCdAvRzepeQo6Z0TleHfbjQsQ0rlnScdHvGCgvJqo9aOM6eOZF0WQ+eFEXR9oyq/yEY3aSr7/5YrgrPSfwGYexToXYrhki6jEKHK83FqrcwtwoqGPy+7xXUaFaWQDN5CvBU7wVunqZB7p+3i4oOdya2aFqY7J1mUCyNvFf2P8WhEwBGN9ie7XrKqTy262CJ/vgvxeRbnktS/v9ds/asulUKqOJbQ9b013qUFNgalbswwey2TGX9lvIOvyhx/Jyt+mz84ILurh4cQ843rI8AVQOTBVVgA6RlK8kQe9WVF6YTV2pu53B2Lz9SbfmyjyZNDLEswfVrYX0WELLuq37IaYftrCV4N5dms1km5ZWY4aXxFfT57T/S1HbBHIGkiMJvRJlZDZRh4CmIgA3ivAM+wj7l5yrCeQMMQGXF+RvLTo6ZrgYlNkAOCx82wNBZdn4UQJwjFcC44ULRj4410s3ClS8Wm/y1fxG+pKd0G+Cy5W4Iz+I8LzuVHYBur2LRBFWKwadkiouKFEID4DUxHoOpqEx/0cfWQZXm4gGe8jnEnLFdLR7uwAk9PJPpA/CI4WqN1eadLnl4qW06ES+UzAkRK2L/1gl4Bf3Khp18SmZnRlzpQlNnddpP7NZ6sml2RCUJDlR7152qBxDZcfVlAjhpkJMEeiIcZHMNnlcPb4IXGdfsTDmFavpCWylkvsQdfPd9XmNLUaCdmXbKgyYO5pp881yeKsqG12HFexjVIuW3pgYjgSOcin1dOgHX/c8WSFiRKQ2V+EgXT2HpkCuU7lBJnr1Xc/ryXKkIBIxTPkjnyW0TviyWV02WfC4cPdhR+E3LDVcyaRAsdWFEyjKiQYsPxIsB4iYQiuz3HUpGVkpfuNPtQ1AAK/xK7LSf9Gz10xYoP0sa6v7m3GaQ9pk1B8xajW+GN8NeePQ9IJWdAIugfA1XXlBXHLk=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
