---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAlIwitzVChW95cg0ipyuf1PnY9hRlitgwLauOZyz7RgJPVY1QO1+4XPeJ4U7mAwJ9nvBi1Z2hbgIMt/ChcYQyPVIcJMWavZ8pI70/K88gsD7iUsKnWhbas4lMB0+5sz3R3wY+nxbELkaypup78txbyt1k2OxGc2npBVrXLXvdblMpfEkAqe5g0+9x1NOCgEfHQVUMDYRmKXxNQBclV8s6S4yAXIvTWlplNy+zBUGT90YxqvWcp1uJkOufMWSS7XLhb5m40e/Qrf07w9WnBadimGAXu9F3ZT6ga6K3dXeMRyVeN68baSLDED6f1wvk8sPgPM7hdhlAMIe0AzfGdA+ntNXLDFj2OnSj5aUUHAAXTA9i2Q8o+HRGN0WMZODhl+x1tu9lIzsd4aPng2F6pZSzuFtqBS8WUh5qynV0vMYEIixTx2CNL73lzg8iPFTKetuLeQxB1/90H28rpXh4TqajuLXX8d8Sfd9leoEFdMLHAIHlr/XrgfX8jZu+S1bE8DR6rgxW2kvDLytH7wcRtrl2+4OvRFtBTQqkwPKPqfESU3fbszhL+xjH6MgJLsbSh1mbrtkUi+v1lHy5xVXBaOfkLcyCyBqzeRoOFtSBgppQCLy0m3ReDOpZ+tQjFujh+4dAeaGkp4R6jac0//7hOEBE4cWwviWkDEPbDLPex5i9YbA9j0YQkGi7wxYjfWkvIbJkuHTXk286/9N3RkieEU3yrSK5ebB1B7HLnjYEU1zQarbfZPzQy2JEGJBHpZbzrnr/3v8VijFfLLrAdv89HMlS+uTIPX8s5fg5/OHijkDj/hCYducolPjsX3AxaFTg2nFyE7nsMDHlHjASwxOXxeEa7I3lU+EB5PMxnWstuJXHIjrbzTtlxvge2w1Z6V14781NrDYnRKeh42hILrwuOHlTujGxeM+aTVz4gtBYqUreQjZa7Vo+lVzp/mCHDzvRrADye+cci10NQM8gWSiEOePRq77bAuznCEjmSmOUFlpUdV4+6sHJeS/4=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
