---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBygB5qJ53z9vrewesWcv2WlHhS+ILnG2NVPNRnUpRRnEI8OcHuJtb0dKRDIhXn59BM1jQs1+o7VgOKQReNJhWTzS1zATbcKr3HIugBdz7uO779TCFpS7y8ZRAbpVWWI6+CpRXEqHX2uualE119mxd2KmDzWkGS+Qu0GyDS3vzXBueQsCYN03bE0KKrmZ0hHIsuqMcOzXQRpA+Oe/UIGSaWy9kfI8v+k3P8mLpg8Cy028MmTzbaq77nrn2ZkwcIXbgUWbsv6ITxi792U/auRBtVPUNpzlZRg24OL7mT/6iKBTKNGatEj9wV7M4cG3at0YIH6fffcocYhCHnFmKwnC0lYRzs/m/Hz2uaPEEkgPC/aIpSfP1JsqovCI/Nf4OK6U2sKxCZ5GebpxeArvp6TBvN+QmN+KR1D+Ke7bEyYW5IEODOiMtIURyxEgAy+GHpqMH594z84kyiFma11sqqHo7mCyL5Hhw+TvZ1zY7qkDzImklo4X42NyEHUwTDnBnZrQENefUmwUqKoWlN+sx/Zvl1j0vXcDhl/gsbNPaqCRN/ED8y64ScoxiQqRST0mtoTfAxpOAs+bawYJG42G2TpmdVCpMsdTquf9JH2855LfB+RQeaS7vJe/QI6ev0doElrdaNy6ByXVlCQaN9Z3L/KpTzRh/iwStoPjAOOUw2LKbtDUqbAgsAbHy+nUSXaVtAfDoAmYf3OI7LJTZPfm+HDDXXpwbOnrCn+gHzc557key0Qytb8VQ/JIWRC7gYYisWSIMeJ63ew5kypiW63eB2BgN6qkjxKdxLuN30L08uDtq3PTU=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
