---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCQ3mFCAwH0kTLPM1kO+dJoalUobZGpJLnACpM6l4b0kQjfVjyv8W+CLPPVZ5PEAii++FsXszT+rR1qxE38Rc/okK89+2ZgpwGydwthI3DbUmKfsCzYWwae+6YYeBKueVERJWZHBUY1MWcFJdZYp2Rxjw/Nr305TnBMzcQe7hrMfN97TQ1RBtcVUZA09mIUik+GvPzTfj8XwMSQ6fuwifM8/1dL1QkDjnB79wbHSwhu6ucyshE+4WWKjZxW07X7gXl3Wbi8oJ1Okoe7U79/V5Zw1wtlb23FiIpb4YZKTKhgsYo3Nn/NyyPlUyBEdlCqdCk3Dyd2LhEVxfsdO6xQSgcmZ5A7ibtlIaCWCtC1yoPur1u+gFzF5Hv8YgnV0dkBycqmlymFTJ4Atq8cH3/woCIcmrKyCNI+cbJ2nM+zNwfM3WWDMuOgl3Bs+uEmaEVKV4SPMZuIQTDVp4Z5YcOfVzPobR5pqXuNt4yrXfuL1kJ71tvrNufIZcQJ57Pd59HCBYPnVICTHdUD1xwzUCoqxnGmsF8E4cptOe19LkPde0Y40sAgntxo94X/XpZQJr1x+PitaXfcHsFqil4VqW0zl9OoLDx/j0C9HPHKvXPYXlCVoHLp4S+rZ1JZZdMN5Xt7dEhgcmNNaaKRjYTrNXICbp+fTomihB1kjI0Pv/MJOkTcz+kByM/dNIbouS5u7Jp8SmqkcG/nMYsZCtgKfjdZlJh2lwSvAxnLK+VWB/+BMQ6kMS7VUR9GfehR087FPvAw5718XZvuvS6U7/Yz5ZZ9lfZSRARcw7ChiwUaya2eiTu1DzM=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
