---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBwKRfVBNEZbJSVpySuvkQ2L59kL1Xfx9A0rNs+2h4JZ4kOsjFdWmA8daAWYUjNC8Uh5gTHcXJV7DsM28ZPJIH5am4ICoYhZhTyKKm6wnVQ6QFPplhyK9+lbPcjxBoSYBAE11wYldV6uJmlyFWRtGa2HuEm52u4ytsJxMvzl4gPrSBFqjiGetzCfeZFD0uRgOAk9Uwr3Xw9QHy7Uk9YvanfYfRQwXf0FfN9UM1YdpxkP48DOexz/jCEV5/jpjgsSint42xfay31Pysv15uQGPQOzhIPfPOnqOEmF7WIcwkftq7mWlVxdVmFA/cdoifaDc4SVExbwQmM0zNoyimqY3zspWBuVEgsEwwCg+SXM0atmiJmaJ/GnNewfP8fOHdUxUXIYCgUju3elS/A5nOQSxUCVGysdCM/ACYB2wREF2Lr8kCKq6RZCoPaGO+cRnnDZ/qqE5tHjsDYGJ580Dm0nTciQOlb/262E7M2QkKj79IgObgcW9+cTS6PwiZcnnS0dTgmXLru/jxWNsIrGWPmg9AzSePtoOJpSq4ud1IWQSD0Qc8aGArpOQMbqabyem+8ZvheTkjfLqdtDOSnjZhmcUjsBFJ9e10H5BTVWY423BWkcHX3xxARmJS7YIajisCN5TIZhJp2XV0rOzB08lnKaHqwNL9Vomh3B3MYb3jWyKKGOIXAL/k7WvjxIZFHIQseXtmQvvUs4C4L+VNAbtAV5dLvFiNCMHEFnJLxvXRsNYKgLuY33A7SAde7
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
