---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgB1rzeL8vHjax8SAjmJTCedl36JLu8m58xnPN3cyhmqRvllj0zEH7Ao+NvwRgZRnOHG+AXvSVLDCXZI5MrG3Nz7iPbLfDw+xamGSDM6sDmsh2GYDLhIkzp5OOXLrwkASVMLdogyUsnYwjIW4mY42WwnGpFDgxzW/WxzCFeCo1W9A+pB623TmKvnkgZBuBrZBqZXFEm8bby+xqwPqa8mywxw5Bl36yahTeCr+6GM5tnVVM2EbQEOk0rcBkTFt1PtDQz2H3xLlvMsfUqCQCNVikaDq3PVqpXLPMw0RyASu8IpFGnbeN1GX35DCmlpgLCZJJEI+j2XbXock0SYsmXfqQFrWNZukCFsxSBtFN8kEB7jXQ60A2YiySm7A/rkhuxH+px5MPwFgPudNrriovdGsdcuUOqhw9+FQWnkMGkr1sW2IGiS1aJKcEEQGw4+3uM0tS0hrKdvCzirX2xfZrebWEpiV6zu6NJWrbI1oxK6HntzV6VBde9U1EOJRQcchSdv1si1hf5L1Ci6W++hYqVXnMTa92SbRnFCkwi9Bj0DMAzmF7VdmYATnHnVpWBzkeNI/6rfR6tegI7HfIXsM2gTKA6m5glol1JdueUTa8ny+rdS46mSHjxf5djQKO7t9iEscfKANgswA5EQp9Ow+G35euEhheaOkBQM17O8h8CNryUYHZb/8nPECBDYqibhgSff2iNMLf2fQSlCt0lwIVYEvO5e+B9B1S6uFfch1z6uNkAQb6HWVcqdB9y1
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
