---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-auth-secret
  namespace: flux-system
spec:
  encryptedData:
    password: AgCWEUmrx5wBdvgQuizxf9+s7d1ib876h8gziJLqn9sQgtC3Pm8wBKQ7T7U1m2AQxn3gUbA3XEOQHh/tUdHkc4dKQaQZKzrgj/77r7Af3Rsv1XVYIq5WXqVo/lGC1xA/k3FeBj6/ZkWwOxqu1asPBfpDPEBAO/EmU2vrosrwFVzV07Ud5cGosGYBkVx0yxc8pSwwowaGAIsf7L1m5b+1H0aTTuwv67x4KJ4PYaYDVvp8L69xJXG8m7x5Q+L1l3F4rVO5GECr5QUSI593N9ImZ5MaR5DWv2kOg5rUIRr26/Cj3MrwvwLNMweUJY2/0VPpWxd+ZjF6s+uiqcEJLnMl0P2jNpLv6lyEm8FwddSphDHLRSEDvuOxpVRq9dFL5pHuHZFc3FbMsUme1lOEM2beZQk3kOcJG6U9d8mbl9L85iczc7r9kun4nu8qtWHJXnJDw7IHx/qzlIiZwMlzOdTVvXzC/cKtW9qbU40VIRAQcDgKq0qOiueiRwviGDrrNRGgzlJWjspOFHPUZ/s/d6daWtKo69LOP7im4ioYs41wF5QknGnzb8ArUJArebECxOg6SUYDKaZAF/hv/5CG9BHJmLPkbwr6fF6OoDMw05t2AUA7++kZmZUDwdXVSmGchfm5q4CRfkazkQi1v/nDITcfjsxvALfAEbt6aEYWyqbDchX6CP05Dkp5eEbTaO/IM+JppF6PGb08l9F4dxM1/ZYY5O3uH19xy+GRHpMw68qYgKu5M8s6ETgUXtZP
    username: AgBJPir/CNuz7Vb4zpGCky11p3uXH+6bSMGglOiLmR7MzElFH8UkWPpmCZeVkjCtIxpOvRkRBn5MvGAEi9gSXBlB7xQeuMS5x3dFprHNgN3KY5ob8CZvWnxeJGJv7qBdG2D3Wi8i+DCanWa7qsqQhJt3dgsERR+UsQgHs/zoB5841KoZ/ah9HjmFu1hfJ2Aq2E9AGCiVT9s2G0Ydjiud0AJflFvhnE5EbQ+vz2Vp14EPAEyohecIOjiaXHEsY1psjt58mvp5zMVDkKRqSY6OtjzQzFN5LJzCfwN37QzhdsQNNpd7oZtsxL6NlgKqLtwFPXgREGBC8lSoYFKz6XHkAP/XABtY6cIdPR76kDRijsS14+b1kKSbyShEwXzpvgco6GksAFBQYo+8V1AjOfQ+ZnKJn5X8oO2387SoZaY6aauyHLTX9H14AXMb2DvN/mU3vnsSMVKVu1eelo2j6zfn5RGghf+UL0kA41fiGtb8eOWuD0UqRVCSeAC3W+X4DkzCFhqnE9Uj5neWya+dMiMLHC1H9GhD/Fklq/3+f+UyTTLZ29JZHwCTSnQSuSatHTyFatOUc6dw65kMtxDJmzqA8ZzF9kpMNTGdtlqLv9ENDN9BeO97cvYr68DY54c/FAQuo1lV4lHcEdTYe7S0FrYRrjbbugz2O/FCVIWXwg23Kcj/vdzzSwsXBFI3M4qDAIDUjgXzfEk=
  template:
    metadata:
      creationTimestamp: null
      name: github-auth-secret
      namespace: flux-system
    type: Opaque
