---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-analytics
  namespace: services
spec:
  encryptedData:
    api-secret: AgBRDMXxvengp+jgZlSanwoE3yyfZI2PodWbLZKUQC9rQCG8JA0RGX/TqBNWHcSc6OrhI2ye0vS2mkLCkqZOLUX0hczBIOL0FMcXf5/Z3UnznQUsGjvMs6HRkdjp41vuaWlT7vF8dcldt6S6rtIRAc0NbWFtcg/rYe+YdqI0ridUfJbpm7OtwzweOJFUVBHlNhH7hDxRP0Lj7lcWPdr3uFePecGFPcH9YG58njjRhIz7JnaiOra7U89pBBHFT5lqo7GZ10o/xCBVUQ7fpib3gehlrwp6mwKg/8Ytrx9JLztdU6yTGE/E+6/pF5vi5SrVhL/uv4Xs+IlOqJ+Qzwbp7AqFC6R3ZTx8D1jTAMxJ4K7fC4Q67MZuXsXrcDHuUbeAlTCCn5AgCukX+xpU7aeY+UUMh1o2RcWx2dPJBH/9f6lxrS07jfIigQLtwtfyN7AhQhVedrgo7MDRkaisDuYMIBbHkhC0yu0z+lSVyLl8N1qyXnvLOFNdpt/fleitkrjbh5miDSYg5mT7MAUDVulAshUf0LvB2ZRAMqH6GKJrCEjRzJ60MdJ+bO4+O98RCnJjJgistmXvci7a0ZVbECVAbkyddQhXAfVUfHuuQOJqPp6ImYyEcaNymFrX8YxydXG0640CQYoqV4Clsi5KuGP1KZSGJ4cJNU4ciJJTudYqbusII//BktCAGs1FRqSqPTVqftYGb2VHXWJ9rLkWo4MQcTcx8RRcNMmt
  template:
    metadata:
      creationTimestamp: null
      name: google-analytics
      namespace: services
    type: Opaque
