---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: google-analytics
  namespace: services
spec:
  encryptedData:
    api-secret: AgCySYkJEzOTaxY0s2qf+JrpiIpL/rcMTUpyyGio5akvKAIW8DjBcuYm+t9NvBSy9oD2EbXQ6PHQLAZLD55d8vnENjT2Gw1WoFKnUrbqn7exAtS7KkziI7QAvRBForO47y035ZRTCfMbepNvPkXXZPXypNzVRllGmdr9kUkuslCKGKDve+hjXAIOfubO7H0uD8U1OVp/C+fTFv6FfKiN6m4yHsMyUd/9E0nevtjbo+2V/KIs8b7oqPerfd+gUAAh9YZwMVBKiPy0sYAbgdUoJcvFD06N5bC4jKgZ9OLthtGts3OKx6uiztVzKmyfgBMnQAyC3qGIH+OFhYk2iuWctkJW/Qwt0LgBFl5yceLlTc6Fve9xAqnfCpQ3TAPVDYMe8KKuV8z0ZMJ3lcV0UAXQ/CD8iasHTza2yGDTrG2vs3hEoZxfnWRIJjjP+sTkjNftuBJMHLRwej+Bc+8TESwM0H41VRPzY7vyFrxMj6tOH6NW9Ildo8y3D/4aXv7EIJjMcD/NqlQoF8WwlyFYf5DoOAMiaBeTy4wUIbIZuY0qBV0eZI2tD4lOz7U+UvSwPqhFiQbUuGX1zOpud/bNHJuJYl1ffyAIgyuLrJ7CfLVgw9PHWAnmwn9q4FBZE42NfESPIDWqDuYIKN58iWq4EnuAW2b9VeAuObIDBDMwSH9LsSY8yzuFCFkCq5UMzUEBswLSVdey6mBF0/o/8pMAiUVSB+YcyGjr5scx
  template:
    metadata:
      creationTimestamp: null
      name: google-analytics
      namespace: services
    type: Opaque
