---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: loki-credentials
  namespace: services
spec:
  encryptedData:
    password: AgA0rcuXb8SBeMIuipFkG+W12ywSpenwpbzV6NsPqPz0K2iY0W7AUuJp1FUJewzoQ+qDTmLzqT1Pkr41QI02xJeJ8amF9SaK7US3cqHAGL2Yn1SpH2APWvmMwDp2T6b1qGsHHtAwuGtldz1c+NfZvf7VHCxnRAlPod4/XEax8ESeiwX9zOEzHEIfCcktiwF11Xg0e1OjJ+7gKJdhySgU/Ut01CJhkUkADeJg+Ilk7cw0GhicQRgVdQZLWYt7R6zXqiko9FTBmD3c2uatyavQRgV5woJrAoSbkEEiZ5dYqlMD0HD+IUdLBDHLgxSk7WelJsJEpSSkogFT99FB/Tl8ID7Y1+WcEh0btjt1NwRB0SE5WJSvzn717VB/kdgNZUKaI6RX3ob7KZJj3VU+ssVF/+rdsH+Y9ACmPL6PlepL6X1sZizV/WSmO8jX+zpR58E79z7N3WAxF8B7NpZPTFvzsfs2mzx71bggBEXBrt6uhQrBKUdayNKeBToD1e7hHTHe4qQ1Zu+kOm8TOgd26eleO24adcoTe4FxPpCz6PaqmvDH6ZamiqoX0nLY0VODZxXmi6A3Xj5SvTzMt3YUo2WKN7eHkKGn6pCcoGmWg+ssHj7o6gBRFrhYJIXH1BhrSCKv/np8sjT88wDwQD1w5lqbg8w0ziUR+fJoU5jAnFwIXXmXOsfFGCSEomQba4cDw/iaO9pvkwV1vN/69sRFbDw=
    user: AgCg3Gyb2pUa181s+f+V0s7TccoycXhJlh/jpsmrPHmzyxrdNUDbykAaOrKKCcWDB/QnCtip95P20jwTVBDmRK+n0aO+T6AFg46CVrS6rOPBceHDHRMZK1nWxyFeCh67ebaqMNN5566J29G5k7k5Mnwv74Qo2KKqQIoeyeW02ACS+EfyoeuHaTLme4gpUFU/rMmmDsk9JXU6aqI6Z0nLssJeZzIDgURc9psZWTP0gvs1JLvP/9jU7Q3vvKSY5TGvPKbi7pURA2GpE3gNPhaC2iO/v+o/0HJE867rIZ0gEw1tuO1jl9lwmAr+W3za5pb1s3G1CMoPJjJ5Ad0bN5otVXRVKChImxizaEdDU+0pz2gOYQBp+2nAfpjjVBXW/HWu1zkRORI+jfhgt6VTzXY5MpO1ObTTN0rFb69tCOn2AdUbuaVjxjK4UMkE6NgYMG9R2J6EqRp2i4JqsKUV3R1FxOiJIyHef38o3eBxUjtUFPW90yZlXhdH6rwixrD/TmcMItrIspHHvBFv3U4HCqrONkhv7BRUx1GotDdo4+zpGurRIpE87AAtQdgUZ+amTz2TC2NF5ShIxt/aCa3BA1NeP9st/4oYGi5HxDmiC2XLfCy7SUTPwBnNW9I/yyDkcUThoWDh+LMucNoezch+4NPIK0XRx/eyMn5g+SqtDu7rMU9NtHjzoUu3uE/uwsjJChtFfA7dMRWB/A==
  template:
    metadata:
      creationTimestamp: null
      name: loki-credentials
      namespace: services
    type: Opaque
