---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: machines-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgA9WZuwWvTuZAjwnHsEO2X9R2OJeDSxx9wwAyv0sUY17PCdl/IU0CQFfTs6dqQSfrFQeUTJY7NWB12hKCJMkckc9yDPW6zuAYKjI38yUOyx/w/CgLUnJm+cTP4qFGoo2BHbETwe6NS0YMZ+RrWqokuVQCwp0IoruZKmMju3DKcE2Pfm2sRn0H6qkJk8U6XGhYdxGPX/ToVY4yQvfkvWa1pXLjtXMuBn0elPlYwdJRqMqc2eIIz1Bl5D22RQWkkHHinwN0uj1rc4RCu3Qw027ST1PvcoP1M8NagR/pUKWz6jzsjSQYxihwMvKX717P0ZX+KcO6WvJK6HBp1lhdeSKTfHMZAozsdKBgR0nEkZMuv4TNINXeR6PCe31q79IEJvWmmjmEdAQRJkmI66e8UTBdi3ogI3LLY6tfFFTA/CCrzeCPakj316pTiQ4OamFyXegspGfdubVnDfdXBk5j++vrBdWfP3dk4oPENNDWZ92sWy+mxy8A8OWkco6cTGL5x8fULUgSgCIyS4KjfVHT7WuhbqtJ5Kh/T84bpPHWrYexXPPwi3HcwGa/xd83R6tJnbegzJ6n3au98piMyWnuYFvCvHTSRp1y5XC/WaMxtGyagSprDMdsSq92FZZ2I0kFveFOm7vzl30ZUxJvOGHEekxSjAW4Bo6TkcL58q+QaG2JC3Gt8cLOCTYc/o58rnswcKZXAkOzMHqVs0Sb8w+X5Zt7YG9dTed1EtKWM=
  template:
    metadata:
      creationTimestamp: null
      name: machines-db-credentials
      namespace: services
