---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: machines-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgCDYt4Ckx3S71f1OUba8dXBikDtv2lGUhS3YeOmkiLGpjerYL/s4xLqvRDJ4eixaeJ3W7WydjQjx0YBf11R60cl6AxOZYcTIbmbTvaoohC4vGn21cfe6pCR8p8PMAO7kl6SHBAqHyqnDu2BVcTBn9DgpA7BMQezysUSLjKOhdf/Jow/PBfsEi/PgcZVl0gWzJKmRKKn4K6D13nNUzNuhgmxmb54Ksqi1f3BUZ9jpDAocUB27MoefI5Eh3M0/dzVdzFXHtxPpnFfUy2HR5Hbk3+Fd19DtGjgvkCmR0JC1RWXxFI2yWR8b36OyFgs0Duu4jiVG52kQ+EgW8NWMQgZJQq3DSOv0N6MxUSut46Tpsl2gdq5zDJAuafNsrxhcwq0zcSgbuyUUQn5v1N0FsnziXpvImm511ju8F/FnGnDSWoqTNCiFNK3Rdur9OPeC9k698p3WiDXK3GHBCnOf3bX1Dd/DPdOta5S9OQyKU5lHMb2HVpF7M2qmlSSqooA3O+jnN0RkV9z6V8aDmDP72X+9lNO7jhkWEHSIajHRyNSYd71jMqP2y88Utu/F6V1nmiOxFfqpVYl34FO4xDTTYSSjqNE208lKy7n8WXU987KsO+9pu/FUaGNlEa0oW2Tf8r54YHFlP/kZy0P/EyuGnIbuGygykcBG8vmEzx97UmrMjrabW9Xkt6Ayj2c4fbgpgL1MFzg7yWBbXcBFMSvUAfpygS+l9LaivzGP5I=
  template:
    metadata:
      creationTimestamp: null
      name: machines-db-credentials
      namespace: services
