---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: migrator-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgAAFaYUT9wHBnyqiIoc+9eV3WGqAY4E1ljKpVQECAglLd1qxn/GODY92wzNK4kmcq6Sr0jpxXCpxzactp5YYRO5fn16E3vhWxqMHmL+ayhMSfMQYm4ryeqy/hcMg/3iHXoU1Xg6x3KBC14Hgig9XhGsCgk4Vzl2mRkHDxLr2/lGZBWPokhcWedU2x/hcRxpKnSoCKL0oUykrB+smhDVC9JlJwCxwGzhhU9XVb9mQAR0TO+WfzJQGjodKmiMy45T97AN3UFtIPjah0JBLYqKJ9DRBUVtcNdcbV1ohNNS4u34zOJ+R2c4fVR3Qn9jniniLx75uOQnZ01bz12gPWlBtPu3xF98yJ3hD5HkT1DqbYWh7G9BPhS+BfW6uYWP2EXNbzf62HaMicGNCuLbE8Ej4fGPwkwkry22RCKRJeA3l9GB3Q0nrSZdq0qrXIMymMiarS7GsJLH/L/qXerBKKtotdi0vnwezHCLDqOkELXLuQMioyFhlHKiKoBLODkeuovrKrPSwECikHa2esQtXCaYa+RbdUlLysK88nk0S1pt2RrYQXaRC80tekRdvZHWnzqRdWxGRjX764YHKKdtnTk0VJDDWTCNpCkAJWTEaAon9rfLFrUT2517Pnxko7HcQIYP8QJsCiiUUeVUyon4/1IZIVlxPH612Kx4dprDOTAdajFhEC3icy+sYttf76OOGG2DkxLVvA13qwHjyJiiK/IMCBZeks0YT8jKoDQ=
  template:
    metadata:
      creationTimestamp: null
      name: migrator-db-credentials
      namespace: services
