---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: migrator-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgBkLukS+dfIzNIvyMgcibtcoN/1MnwoFEDRpLV2grFnfuwAOaif4HWl9rs6l7EJC6FfsN42SuUR5yf3WCdQiO0EbNDlMMXzaR3Gzgka4Hd7yvA6XVheo4mR0QpFGv9xqsqsMtwUkhajyB7530h5W7B39gwTk+aOgDEUShri5ZY/rOalzFrHhtllD+NweFGAyAgaKGWDm3olzykkC8MBxIz6OQRGCDzMblG8aNjjH8UPpgH4e2eEnR6WcvOuDa5ovjgUw5G6+1fglv5eNcix6GV1qK+OYs1ktbgsnkHY9KYxSOWh8xnLPD5GIbdggdbqk0GWMIm/DHokFU3GFz2W9PVvF5x2CQZ8OYWvz7eNWUjOFbqZfIin8G6oPgoOPp0b81D8bxc/rLrsDYhFXTq9sdmhGiTrc3dWHPJzZwsAJmzn9e+fnVM9p2aMFclqhPsiq2MMkpcOZqrHtFOrelD0E+75psyugVvoXuGot+aDaT3/zapJx32ay2oOaGfEqMHPpFxfW2MdThuE7WG7964uiifoysb6bmJnBd6XR4K+TdqMA5oRriWp1emF6/66W2zsVyFspmKVaOGxpAquJiuX6j3T4UK8CKkIogU8mVFmVRh12h+05Ybxt8EUr4GFx3zoh/NPOzRsbFv6vVO21DM1iAQJH0f9eSDZ9ITC2UzM6szDAfhM25km/DiC10R4Rg4n7BcGsldWLLPHNJsIVAHC7zxeMJ1q7cG2Rd4=
  template:
    metadata:
      creationTimestamp: null
      name: migrator-db-credentials
      namespace: services
