---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mixpanel
  namespace: services
spec:
  encryptedData:
    mixpanel-token: AgAlu8ZnYAl0fmCusyJr45qJbwgP/g5v3VZnSt+tT7hl72nmWc4y9GXADNqNTo/LAK51imyZGT/VY9pQXUEV2nl/OdGhBjngeghpCpbr0tqJyuw12CFOEH6EYUY4J0NdTp1CiHKdepdLJUxVPgsmkTAewCJoQNjQQjNIWK1qftEiBI8PmCbq3ooW582kee6aYEtAILrgyc4yjUCGTjirpX1Br30hpZhqvyMCLtSVk7Flm41aNnEvW0xzWwy4L5RLT5x8PFDfmGHIML4+CuuVmbnga7cxBGCkh9ISzKhKM/ZV06HgP9FO52w+7Zi8hedhmRJygXN2DssJwiAuksN+/q6l1I6G54nD5NAII2PjRnKdC2uKSDVn3rovDwxTMT9/WokzcisSQVRHrHrXnoNJIY+Qk95xoKvR63pptnLHOgiVP0ozf8CAO5FXRads5vK+H6hrirlndePbhx9phidEMTlWJxEalnYBjR/iEBu1+c5WQdCt+d8COpuS5c8J4+xqCOx0bK+NXzD0SxNtZ4jwhQWZmG11nSdSzUtLWuhnonyT7lBHRTbN8NnZ8ScAQ3/vzEeTZQQK9XQJu/7D0Fi4rrxZUcp48qSWEr+ViP1RetVXoLasGm/Wdtjs6jggGOFR0r9xP6i90COiS0s91LLoJpphPFijHHSbjD6E7AiI3ENF3iA8UjMO2sJ1Np7uxfPOwVPcWtSDw26msfuj5kOVdGyW4EUOf/e4rdRNFe+brSgQmw==
  template:
    metadata:
      creationTimestamp: null
      name: mixpanel
      namespace: services
    type: Opaque
