---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgAhOGid2DIwsbH4fQ+yB/c5qwDJvO3TOII9+INOFHIf5JHNmrfDyEggdVc/xeD/e2Un3g1idsvPnXXxDmpPj2hQW24Ckdo48uLTWdWjFhEb9QPLZR5zTqpZ0rO8NpQrNU2yyg4k5/Ex0ryEkzgJlW3oaASxqdzY1AImvgTBeCmKrzPD17lnxCC675jB6+oHOe+iwnr84QVdUGbqNjWfdlPKCCXrsv5YAo7dtIoRN+JR0qZeYaPMtqybAtSCWnCnYiO3V2OJruwkscJ4wzca602zGk44CJ4U54eH9E2lUTQJ/Sst6vJa9WZDp0QMxCuaHvkcmg+B3bvLJO2Ea6TGiEZUzMCgXNmeI1N+JBQUAbja7laxIFNVZmpMSjgW+M+Th7b6QDkbHfkOvF6M3U/5W1Q7OfP8Xbt805KXnqPI6/EarqijOfAT4AdqL6o7v1xOZOw4GtMPqj6Xs/suXHCNXV+mvS+hjcbKm15USZeKul5qwczruWtDBpW8E1mi8dzrab72qkle+s535AwADe9EhQneb53Cma7+VcuXWgYH9vLR3y7nS2kgVe7ha19OLmkNIg/4nrVFFVxeLq6fzwsO/+dodqdoFZLLR0ZAMfFSexXdL2wt++kumkXUnsqpo4jAMkEqJhJmlW0Ga5DH/RU+YgwfgAV0VvBVzuWHWmwY8Q0Bh6Z/2RZvG5JcRIVKKTD3iHXb43xy3p1KHdls7Bm24jU3I0Q0dOM1psw=
  template:
    metadata:
      creationTimestamp: null
      name: platform-db-credentials
      namespace: services
