---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: platform-db-credentials
  namespace: services
spec:
  encryptedData:
    password: AgB9DdHlZKlLVaurtb0AnPkQFzoZ8XZuGMivkwV6VZgs/SFk8oAmuVR4y5EOH5ClPie80MrsuXcQCTPDY/g7o0EdKyoPKcTo7oH7555JB32wkvknzLxj1cFKjBOeA7ei8e7cYEH/PFFZpEdI8G2WcDtSM1CqMGYE7bnkzIlkSl2IrreWAR5Q1oV7gTabkcMDzl3w1W6Jsay+GbFVUg6dHIMK05upxkwcMq7+L1ZubtOEfJb0Y7oT1wEExNKiEnJJmF9NO5OIgqU2IikKjgAVDsr4py1FZaxEeUIM2hrr/vNqq+8/hoJphYMjvKrxXT3g31Q8b/h8B+IlumEh6+mSc9DmZda0iTmpGJchP9DhHpPB8ihq8LgtTouYtRGMCGd5o2nc+nvvCoMNgwEif4tIWcy56XY5Q6AxuROH+2iFHNtgvNB7y/zqId0IgReRhtpsgLdrK4dCl1SdOjB82dHRk+fBl3L+45hZGcrt+FU03LR4cY3klvJ3s4jEy28yl75x2cpOJHetw634PtXZY82w+SWjZw+qS+Uxm4+PLsO531xuTK90v9c3U7IH3Wf/yXFqx7L46GM/1TaoyAfrt2ms7lCT9nPAEtgYrVJp93AfCAIugbgf1QLiaeWf3LRgPBmpiOaqi7ymVDvZS8r2izN/yOguZ2/Q1LVj1PO+aDV6k1s7E9uZmW9w9/gwLAPK5qL3qxWlt6NTgMXorrYF3q/qq9r9O59ryjU/W0o=
  template:
    metadata:
      creationTimestamp: null
      name: platform-db-credentials
      namespace: services
