---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgAIFCP7CIV06LhcuHDF54nzqd+X6w79lNqwNu+AD9upo577RNEI5O7Qnx1Atq/e3BgUVNwX/IMOisskKjhW18hFSDs49bWV6cMgf9edZaQBaXYc1h5yEh82D6/uODXEdv2LmklJ5AUy6T7rPvEtoz9MCxKUsLMge8XX1bBmjGtrCMJVT67Jiq3qyu8XvtZy3FTVQyC3UJx03A1X1+O0ecSM4aUlteBrksvn7TP6sWFMLN7nnVNmx26P6a9/5AJu11BnM5FUkn2kh6KH9QDEV7XBuHJGA/sPhSKd31srJ3s+kzgfy8Qw2rGCMjY9K5lSjjGn0M/TlXl0C1PT0wPXHJrRcgsapzRNmeYiTL9a6cT5jzgSKvo7iU6cxKoaeRqt7xht+dL/P9lq2FwBnW0EH19bu/0amQY2dQzSMSf6t04FZyNaHegLgp1bYKms2TfVCE1aDfI+FBAV5HeBQ0Mrp2n1Nrv0vZ/G0xYQGiMSS9T/xrA4Jt2q8/k8JOtzugEHFuJmR8FWNo6ndDNYqRR/jRRHzn+NhmERi6hhw17/DPBfeQQzL9XI0DyiqmFu5+L5j43hRF0QnGAk8Us3iGdFxx5eaaG95z4euYTxjs0O52NjfqfP4vBZkPyM0P6WSxcaSDTrTWo/yvmH5I19Do9NAgxNYWZbg3t8jePbVpw6wnySdKbpAzJO0DfQpgcziYtX2krYXwpwDzZg4I2ZkCgvkeWDmc3/I1ynjaqqsjIxYYplim9Nv18U122+cLleWb8/J8lKVpdoxLIJYmX/HvbUVWupx+oogxAFxSRxbSA63751q2vbnUEz8ax2afCia/C3ANWz1NZRh+kHJ8XOYvWGRIYdZoqc2hnzKL1+m7PxE/roTp4H1+4ZmX7t5ZnlZqgMSz06i1YqcRpvzADUOrTWeYo3Ft6K8hN8Un3Ty4VFLSCFBcu+MQFoyovujlYQexs7bcGdvJoV+OKfoTiMb5VrPuo/DN4umGiOal8labhcg5I7M2U/jXdSY38=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
