---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgBJOH3ObjcBZ3vPrbPS+XLKB8m3pCdwtq9JlHSoF3nyPWdjWVsDSBAahU26aVeqUPcl74XDVdhZmksUOTHeW7AONkxWF+sit5hAeYqGapBFZ8lGn2zchCskT0PKVHqRJSJWYfjiArahi2q4cR/7A6n+XwSLDcton4m+9dRWPi9bEqi3m1oRnabwoU7ylaB1FVZALPFISuCA01mCHkd18wmxWlHib6XiWwC6lhBFPaLl6RTVuCJs4OmvVzsJNHjcNHEcqwBAKbVjLPPo9QX3Alfzev2pbWZG++1zEmSC70oxsYHv7K5RtmbBbSeNvN8vSbPgZut1YclBKo76+KLWMDW5ayKAx3njsdwDAwIO4PJXzF0JP/Iq7ADq8lw5b0cV8uTGp83PN+Ptsm7Fb++v4uwHGsthRbJrRJJt8PgDTPslbenEVOrqOfzUvbBSIJ8PPTwqxQ2HfgJbcEMN1z7hPmdM83gl/ocJXuIs28DPqSjORMMM4QGJtcuXFdT10LZ9lk/2OpnEjl8Rhh3G0z5pLfqvGDnUzBxsfyULGdUJluXxTrATzvUdQAXVRFZn3+cRsyH437VYjVGqs8BXI3xHTQ1lCo0zvfn9+myM1nG8+qGjqvVsG9lIfHEspxT8pccoT1n5jGuCNyXtK3BzEmCKSpNALOfU1Lqjuus+XcY4knYR+JCrJrn8IA5OCidZpJVr/nr3r9VcxqmoPE0Q6a0e+LqHnc7frQAxkL9F8znEUMACM1YDMjyPN6/CUkuWl4d8A2obpWfqMIYC6ZBlDwh0U38GlsO4RS+2K9LtuSssdDYH8AjBLe3/yN9m8mJRHUn85Y/PBAmV/+c+BUePLU2oMHdN7U850rocbH5JX/p2yZWvE4U3EoQB1of48kqNa3rTKDG5xCbv/2Dssx/oTG+zOXWpZvvVpAPZTvpKHc3atLpXxe7MqmVXSaLxSSRG1XvbqKXLeSPttPX4vodQaGFbe1ZSY9968OqLVNFl8iRvZx0EoWf8H6iq/ew=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
