---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCX/2QsPAAAPXzKRdgsJ6mRsR5sMTWxgMaMzukTYzRzXd+zBp1JXrHnE8sRldQGbAG+eopiF+OoYNOHug5BxtTjDTgl0WleFbMBPQ9JVhyDUaXq6Fj2pmG23oiE4fTuU+a7uWKtsdE8rPMBMTPcHlU7OtcA3VrVQsDEgfh0MlE9fAIMcbQhtCNA9Gs2oivAblTBJOaf/V7hqMUq18GiUalZzA2qfa1iOZj0+4nyigC2ULODuRBiGbMP5y7xBJZQQDl1nDhe++jvtN+auO5SdbjQmVGj+qD19LTIomIV+sx1uuMN00C4xFl6bKg0bLFCN9FXN57zya4BVseCTtDOwb+RTT6pM93ABOWqXSf2ool2lZcezk/Ph84wbT0+A7nTBgwbrcpSryTklyWsQDXUa4kepSMwVud36aTnUbDKr2lb0w+3OA3fVKe02Ny+DFrWzRms0AGrIvPxUhDzLi8s0O1xpZf2yKyoHS18RVc+SegbQXLGLfZhg9m+L90B75GCUb0GYFO+5qx4FCVTXdDAawb1MJycHZHfta2WBCECCXoi2PLAeT95onzocEbeopFhbPy2gKyVyLwR5h3hIoVGvUErOl14eQJbt10cUrmyUxM1OHKE6XhD06qqN183FIJQoJAjd90jmR5yBEDCnUd/ihs6QluMJIZRE4D81njVEBQYHbIeJfkzlhaUAR/ab3HvJWYTwIwqjPstNczWyCiNrGlxYb0EHl8FpDUdtTqEbC7CsQDGOhYHYNlTZjEE/4cdYJiAEpZkvi54OBeFJ8rqK1Y3/I91fnTiZo3HrW940DXY+tXd698GQzf17zMfvJCaXFH9bTFN7igNnhD1Ws0opQr/oRCNB7nnFjEULvRNG7WseX/DEefca6KnVALORTeOSdL3xN4Nf7w5aMtfdlvIauib2eVX0nIWWdksPAjoXeg5WarYtyA7N4LQ6RAnLkIgFeS/xLLZxjtsV33N4BWYlq75cEH9YlHUgp0LTYtpK8yrBqBmWthAbn8=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
