---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgAQ8grg/6W+dPXitl0ydygyQjn96JeXEu/AxsosVLVlr+cYmvZVgIk2wK84ucf2dqnZNQWwEnWChWgeUExafb8ACZD2Db70gLulFUnOMlR+RnYcyGANRQlR/WsQ5kpSYZQ1U6ey4DJg2mDnzmrM9RnIwQOK9fXrm994zt+1j+FKejrhWc0gGIIF/xatWoGhZ/81tW/6X0pA1y+sN9MZUfB72KYNldJ9nEuuMkOVL0fakmpGXPSEx78vRsy32MTUATPwLA7iXlWN6K0M3F9r5Fum6TqZ6HV+nD6X7eoZVQnI7m0Mp6hLZEFlHwt5AOS7GO4VkpH71sUZZok1UNRumO+e+PF40Fus7OdqGayhIbqFW/5WtTEypBucxQBboWwhmeHW8GgR1M0KlKMyOKJdDOrD5wDeeRzlHhzvKa9PD8zsT593OrOJyt52/RCL6BlqOIOQbR0Ro4o5qywzQUG0uBDSKFpKxilfHRGc6Wm++vRHtxr7KVA6jfKL+zIp4sfCmKOQT44y9NlaOYEbr8p20gaJcSDMxEsFDGraLdZa1iqf4XH97I+7WfUO/snu7kfseBp9tBNLj57n1gs6EWMboKdfGamftHtHBa1Tid9mJTPIc4g5OEzNd/zPxvQSzPSWbomFOHRBUtX+/QsDbCcGaaZ0jGDhFPeJ5eT0cjotLwT+omOdwBN68tLGt+5IIT9MoX11wfODqI8/xz4MqU1wDwMQwlNCcYF9Soyz08ID/nOFnwEfGF1fH2S2ZT9kOs5s9n3bVUWO2MxMCrr9aBKKhIYZBfkEKuoTimLq+obOuVugFxErxOj68m15X5wnmKuPbXmKO2og8JhjgdFCKIdc2uAW535vGi8rCJrOznEvh6hGQuVDl91r98cWc9n4eKnNbjq1q0F6bHH3ABhFxYlwM0NR15oYbdRdH9o7Q3HDrrtDbt3WegAiAtwscDxLjb+mh2DeVkFpfzQiglEQG4/UvsUoxmjNQ+gd3QcsiMlggFUIg54IccMyoP0=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
