---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgCjXZbDM0eW1753DIbu3P2fTvH2mU0khyAj4Ez6C19pdii/BQeydjXuXdRtjIGCf973WoXClbaELq290U6tu7GMCYC1U6AMvQR9l9DIFIIvvS7CZnRtRDG9ELi8y9CXIGiACMdQJKisEAKdDR9mkJnAI+NGebBGU+VBP7adv0luW0HYCtA3sbZeEhFzn3P2fSK365ULGZ0g71Kr3CLDRGSr6Kec9Oixi2a05RK+CHkTwZL6Kne2VBB/sS2t9DeemqZHVLbNsOFQRJhngxEuABvGibJh7lq6ylrEXx/1JtWNkcHH42HUimdRXUv0/7ezzjZaDnfRQ1BIqmUUfmSb6tC/uUmiFglDuYxgLZnu5Ka/QMXTiqz3M6E7Ek1OPzqohPM9AC3RR0UUvuxrZAYIhQGIOxbl9MRDODx8O8DY2rlOnCaGxN+9tZsDRiokyyjEWUt57VXYJSkPMBsXbwqcJjghYKwRNCwRP7f1tqs2ZjccjWyVq80e8Q5pX29MnNsf+6nfA5g/ytDyGSjvDfGR/T7Vuj05ahvIawo8V/cz4xbP5YGNfUnAefNqWmNKpMVQE5CHIB7tZJgGm3QQtANKABQpQ2gp9xrd1D/kTSlyBb3Yo8RO79jbrjOX5piTNY84zvD6zpX9m4/1LtNZTrsozklUcaT7rcs6nbgFTeIRdURcIiWB14ep2vR4ZTk21JuipBYeeo/Fypsv6dvEPk7uSyEtdnsoEGGOAUrvgAtxys+A6R9I6JBl7TmNMh4D2MTtiJ+Y+KG4KtEpmtjpIbmiKP6Smllb8lgFcAPOTg4xwzn926r0Ej+13h62wS50ehjPD4XOrfniG/J/73ikUKf9Ff0iCHiUv4oncsKndzBRZS4D3SBMpt10Pdwpa6WsHd8KePl6bSBjPc+anFLoJiWOUflQem659EAvWDyc9srDOIw4wMpYgIyJG5X15eOuuTUcV3/MLkLUfLIICVbnOVUTzo9U818jCo8gwnsyy2RjXCLAbTOS57raBVU=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
