---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgDCXMW8SMPWkRpy7tm/FuYfIL3WF/5nNetxK7KJg1gYfp9rs7JXMgHXg77aXOU4ailSpBjXanBtGhtK9Arsd0xKIbf4++18qmyrSI9JVdyd4Zynsaup1lZOJ/k04X+7qt8ilXfYusMRG9BsMTojiMwiKUIjP8vEkY4E202Br2IZrcjWE9XNg6LBm6SZ+h0ApTN3aSqZh9a+qgm6oi54jfFly+bEe3xFTpztBy8VDkCG7vm13asJFG2G480++EE3aL+IFP/HlKEWc05yd3mmjeRYdDaIQuBo9hpu+v1x1NCkcsEadHIN0vt/HiU/88wu8F5Be9hV0DJ0ZtSVoygBBGc1zHXfQGmPsi6CRc/nIFu+dq8oK0tpC6Y0YkZovzF8Hh7/ZLCWw0A7o8JatbS3ETCuxTz+1tCpC/FBS/VR7m9Xt9dDXnwozEL/8x6GyY0fMdlQ6Ej/soYDn4OMaRXRRM1f/eiHb7kkaI+A2YQ81NhXC0O8dyTTyeFZMTN5cXAyLMNYkwzwbA6d00ph/v+sQIBLjjEgaZtS9hLkKejPfHZ7eWg/Jqjzdn+hSkhJWWmtcppXbTEdbFaG7isr2mM81pB8PcdFbQRRAclB/p1ca/SjANV/0pXZ+tbC5X3r0vgqUdnxcGfHx6L1iNRfN16Too8uqTarfwasXLKOCs2BEFSkOlDzd5iaezTDtA6/17m4itAP2EPB1hRfv0f1FvkoTW9/xeKyO++S90xcf6mUny+xqV097/EGa0+BUTRxMRGO7f60XCTwLNTM86jcXjyOJtEqUhnjlYQ/ljaOPfEP4tRtxC/QvNc990bMCMWZi89rLCzZpEaRzRK0Ry46d86UpDj3rc5s0V00mp1XGgnkGpgFMIku93jeYhzOaI1RDEzMDpbvzJEYeVqTFkgPBwRp/rDyp/wAWnzz5hvvAZkyyCCNtwWoFnV8F0IefiH21aFbgl5SzIjMhQY1UMJR/e7vfEslLz1/x5IAQF3MaznHatR62nsZM8wq7vc=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
