---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgBteqK8N8NhJ32xWUjzs7xZ3MmfpzatXRic33gNApksQ/GkoC8RRiFN0sTO5fNKIb/CdIYn0PJdNT585YK4ETWonSXmqZBxPhDhmY+nrI6re6/YXMzDpIDwupYn6fGTVcKFOaDSlY5n5BrQcP0ckO+4bPFyc1Oam5zig3RbVlgUXqwva6Ki73AHBKEkGJhcmoPcb2lB7oAMdgDp+PjsOJbQ2SVVdNlnna1fXvnT0uzs9JBrAtSyJv4E/mdr4Xb9hBAwY2t0pqDp/oeLIuBJynho9i/jDScVGU7zHy9LyCGslXihtk7+tWaTOlOlexd6Udox6KZe4R+wJm3QdTHW1VN8tt2WWbv/vWH3JkbDsw6y4yfmH98XCnWVetYNEJs1qU9ib3ZojG4VKlNuG9locvm9yF4hEufovMI0kGK/juIgC9xJIcBsKNxdEBTbI2SKEwtXSUYsLvX6p5ibTE6Hy+WZDuVQu3TNVnxA3SoZ+hfoRBkIzu0QRu4ng5OS+0zZ+qzY67fn8UcsxwTgC7maH9eH0me/68qneWwIbo8VQtzdOyf5tEVNdJUD2a60ll26w67KHNf4H5HWefpaRhfGyIOG6hihXqBo2KfApjaztcnaAMdLPQDqxiqqjV5vXWflTjaQzSI2ygSTvwdz8m7NVEoLUJIJVoPUTPSAR44pDH1anKwWJxg1nj6vw3JigEbES2pKJDggFKh4/dK/6FKmRmhR/u9IglEUsLA6RkntNe7bU4HRn0YkzRaBaq62uLy4y1T/RZ9qvdQnwws81MtcBy6+/OEnbCom/uEFXVP5RBgE3gcgv/VYT1ar+UaXvaAKzO1wKJ5Mqdx6njZ0BbW786wIkESNzGKYtw/ZoRKe8w31oay8qVCTwa+ov7cdynRq+QxtdPVZawPqHDe1INaAhW68ZJr3N4txKwTq0Y2FSk9EzV6VGQ6Tdnjn9OvDyRbz47JoPIsIQT8XmIh4eV5529KVCO4qZOppmxc07BZBehp/zbE2tRu9GPo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
