---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBXfQ9vfpBXLM2fG34bydLJOuky55+PFetfn3y3AlEDUGHick8SBAFidNwshkLIdph6ksLE1prA0wuoluURTqldx/J42gZTmp1yFDcyIFULm8r3J6axjDEsYao8imO/isSCPGvSVRau02aACoSs49pAlAG90gNwVTVPZXN2tSeamzCiTJp2x3sLWOBW6zWqa9EAfL3QpjATFtbEu1YU6QdnS/A0rxHUaOxDYYAOtSVYvD/V6nUn5oQqRvSrkU+AO52FKGZAVc8f4aXTG0LIKaq1iGLVpQHSrb1t2BOumqQRUGs704B2hpkbRCqAqnsh/AmlfKY7W6wzZqNpE+B5J64yZY1PsCA0yVflvUFxxo/lSMxNV/yn9qpOnPj4hyvD4mijwls79q5p6VAorp5tHvHuD9Pwq+ypAH8kNXR1fwbeQfFHqR7mwseElHGcznhsfyJENZ6Rt9KJGrsr1vTbtm3iZfNQcTnyd9PRLpDHXepp9J0sjvDWru5Fqqdmdk8Qv3QgBpSs5AUWuyJklVM+dFwLB23l2AteSZeZr8CU7xbr2DAaweIFW6w6xBDarpeyBSqRmbhoxomHs7xIj+tl/JqdnhvSVcg0K504lRoI9lMuIlW/ySgEps2cijUGts+4e+cdjE3DGL+7QcqXV1grlcwJ9sHQLYgSY8jjZgHDXwIfyYy3rVlhO+EKWX/XAUzHoW/1/GnzFUixESsPi9Vhp5a+ebhWR+b8IkAtLVSl9ws9PhetxVM9MwtXARycgWiRtikPUQiprSW70z4JWG35gi1k5Nh4OjQwnaaQ/xtxeVFn5WICK7+zI96VoYgoDRNB6qeKRMv7ZAInN3M9DIYsa1Z8pA2yU7OCQbXrKtt2NdEJpnlIRaThAbDpD2hloO4o+IUlQasfHhy4y6/0WWSJaHRQlq+YrOQeU/Vhyw90mAtZTNUeAuF+WFYhoquxw2gfYSqrYYw/7+ACF/uwbizJwDg2Cq1aQ8mfCHsOKly/uKmtV3zU+ennAoY=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
