---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgAHNk+Z9BkoJweNZmgCgsoDJGHdA15ZdiBr+vvDde5rADEPgu2N5Z6mAJr9ImcwXnei3NfXcv3x+ILvuEMBmMEfruNa1J8B5aVJuNLc1181GqHD68cES0v+dIfgVyTKn0rhvON3r2zEawwiyaR7xRAR2UsRdGrRx3VXYJLZ8XyOJzLroyhPTqP0oeKplH2MB41elpinDcO8FBt+3vLp97flNeNjCVGNVxm1tGAHmIFOUVu9bFgkPQdxOcCwrycdq6KcJs+P8SLFpuqwiMumdhspi/I+84JjYySBPm4XJ2LN6fEzfAIhNzGEWn6x2tUqhF/8XRJQKDnbsxDh5etyqQ3mFiW9wtN7Qpeu/OKfZQhe4zfD2b3uAc2SLfqaSVVbTmcz9Xlh/y4Iy07bE4D6Tlhe84bUNOWWmHC2RrfKKBYUs+xINNBP3h3hHjy4kF3hCz1QoMDqxAOaklnPHzhLe/YoR9RGifk1I5CRMAtBtgUqU2zvESd7F0UTjkjFO8lyxK2KoGQzWKXY7/Ux7X1h6tHEhQtNQx04y6A5+iZmtXY+hhb4UciCChG9zzt9M1zZA2yntj/wT0yCEPW0P95DFWYTNmUjr/sQF5zdJH42Z/AGXUWs7SNJdYnAIq/GhcdYCBopVHdaNFKbDXAx5KmeOGTJdXy2NhPrGYjn6G5pJnGfESWjgTb48u4lWeJYgJdZhRe4jbrUNm74c15a/T1l501wrN6vfTY6dXu9lVZn83xIRT85XyiP92pIRxEInDu0XcdRI1ekhx1jvncE1D9WtMAuuxz2pMf5NGss7b2I89jfDGIGx1hFvte2RFyyr5dDFeU3tDafGb7CRWy2LgwWD2OkQnpagPGptr5rCvTUYsMHB/FFDt1Yz+nVIKuSAwkBAUa49UkowbWH3XnqKs+bZgB6ohizELyppRiEqi6sxundDg+RnrVSiVpPJYvcCiHvBZOuqetSKu/hImDsAtn0zx0ruJwOfMqJOA+oz7IWE41MSftkKRuh39E=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
