---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgBiounQbrBYFGui8/4JtBr8YtBQL6HgWnWJLNfY95PWzRAJACSQkkmYPvDVDmQTjof29HsZJ+ipvsrzJRu0bRxTQP98y++LZ4lfaGt5cXEQXRm+FNlZ/FwZvs4TRIu/hTIVOXVJKx57YRBGb1qLjRYV9wYfBxtT9Vc2c1rMkAa33agpYuMm/Wzd4dBowJNzee+9JFSFFOT8OTbA1M18CYh/WLPg7B0AV4ioDJesoQbCvnNfQLL4h/dLlg4RogZkpUsGDqdPm3F3AVPQaGLQE/6rXQTZlJ1LAKcELtuNOsXvhXOxaXW7iq/abv25T+Vi/VfU6wHBhEB2/pmcj00q7YyXOfDrL9FU23YOsnolxhtM750i0QJMBXUnlkx1Ezq0kjAxXjcAUgAuiFrBSuTvVCmsQLadUO1DaMFr2Z5Go8TU/TvQeZo+PcgUdCoIbCJu74ElQvKdH8tBs09Q0daZxJpAmxJ/Th6CihiE3lt0NimZcIMpd5ciVJyXkyDyJQ4RkzlylWCWjGLIGiDHLcacSlSiKJNtCt4U0DHWM28BEswRzQUKepr0ugqmD/4ma0ASyLGcHpC8/5RnJEFz9HDZA6DNyGB2qNn3V31I4evVvGEink5wcgakzB3SrRweRPwgOtNwsZW2O4i1TeeXs0S4IhvZQ1bF6+4ukkH3S6yF9DOJVN8rqSmtzdERzEpMkS6gw70FLVgFG+5fkQkHyTeCkI+jP8/STVPypZsLO75ZUUhy7R7reo6DdGaAR3l5Vge7Mzbl6wOjkhnH8Cv384p3UZ2pb/qdez7e2Npjc/rRSjopqOsLvcejbHOUvIW3qmlhDtM0napB1s4sEdjpusxlIhSYM6UrfJRPA/tKOdzU3zKrzQGxKGU5ZwuZ2U++5reh9zW7bNn6akP0wni9FT+DlL46VQHbYHhKF/39R5R8PSpfoBSHMzJY/r4KWG4rAY86fGO8f066UZ8fNXdxNpytOS8DsI6Z3ATp+Cje9AAijwZrjKta5ZhH010=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
