---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCEpdyjehNVYEtfg+p9sR8lAkgMAkWY3K9UYrB2Sf11jyYqHluIaIw/Uo6AaK617oKAzlio9biYNVC82DTaYt7oBEP4S6U1p9VRFecz8j+uynHmVUgRKJoZ0YqcyF0fl28bsi+oSzBpmEJRipI1DxLupm7gVXBPpeHaD2YeB57bMa/w1Ulo85P+9qeJs+o+nVRPhNdIPVgZc5vk7K0Y81JRFcUZy7Q6BqbWJBhZSbMaYRyCCgjWuFqbV9MOQI1a5+peDSJ1P3NRb0dbn2FvP3nbjsv7PAdq3vu2agiq5lvAnhEzIglqUxS/CVc11KVQoPga8D5ZN1f7Klk8+HnoHYk5CS5gC2ssxc9WmI94GbUfcOXAHD6oZynvz0xX59V4R4l3ZxufLyTmhkSge3A06A3Z9waXFMNVYtDhVtoLhOIAV/4+jeM47+nnMtBUdkloUKfluSO1fESn8bGpTHp7u6VfC46SY50SvZyeBr4hXjmZVxPM4S4F7gYRdwvazGc8aJX59nRadMoBdSl31JXJiMMYNtxMNF7j2ZMBxRvSwaycNzaaKtNyLCF72h86sZICJcza1s1uKhNKJNkXU3UHDFdn/envUf2uWoE76iQ81ZtuL1khNqQ+yyvtfmwRdD6Zzo5tvUJeQyk9u563V+I/+NixguMB6DK+/39E5jVuVd8dGouBZNXa4MgO6+bRzraIUwTJ4pbbMCTnOfj0iDZuPdhuQG5cJwpuNL+OIWze7kIFyGrq3QFtQNS9Y4hfmWG5uMFWLkCns+y7QVULYot2iLmC5GUK6Yjd3noJ9Jund9VhcRjfPTd1SKbtHbwzds25nzu1NFnSXmM+m6/Qk/pP2GwZS+bymdmrojGkr/4jL9wqHb/dmOAXKisadUf+Ud2MXGXELjcx/BMxuYRKEWxZcpNXPjBaSHZvZcRjDkfTfwg8y63+nTRocTpOD+Sptv4q06wPVXVeoGJi5QJojLPv1PH8q3qOT39Q+2ATG/TpUfyVnZNb7tLy2FI=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
