---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgATQjBCeyy1BasOqVWUaGxKm99IO4/532/lDo+K7OnixZXKPdzPRpJRFjHIdRVEfZfMGLUwnD+89MAOn85tY/Pt1VWx+A8TLYaV7f2ybAB/paBMc4FTHEo0qAUtrYSrrRDtSpjNkypn5mCQOJKcjMmVdZCLvN3oCvIhQVCFd7JADwrd2/fG1QjdXbtfJF9ZIjpt+kqPEtwpWk58+2vnKRnbLGC7m9osOxBTVh6lm+hoN7zuGZTW5o5M9+/UHveGL2J9WLjX9J9OVxXhrlKVy/Gc1TmkR+aDT+g2VgnW0Ezj7HruvNGnPAcBr14ktiW3q6lE1N9pfkhTVa/KfYaAJ0nD7udr39ciSx5GpUMUJHDu7GORSezJo5Y+jBPoI66QthxgYEZsAskp2I0fwFOV++WRwGciq8cXarkHOgBjqEdSpUcIC25dJJ+zZqWpd9gEw5K5Yt5JD396aczoFiwX78l+EKR8w2fDlWV1LLpqByYa7LpsGTWQ5vbPcXmGp2PIZ3PPQOq4FAdaHUFa5sDGFzx93o25Hr60PsfbHQzIcSN42RVb1ToGq38IDEB6KBSPzQdMMuVCSvs3tlFcpkKotfrbjAU6oI+QKkXU561ykUdw00Pt1wtBkWloIKArPnuZfmVcz8rbQvdAxmLPD5j6mwxZZAwYOJG5RfNBL6yMzot93vIHVzeCn0bU5FKYc6jxYS+0Fpgid1cKzKomz9ubOPh1sWJG+7SYJ5daMatFFaX3blSIM87c2YI2k+E59tIgAyZgn5oym6pprIrPjugEAsYXO0qiP7tIbJCkQc5l64Pk5GhG+5Lbn0Et53qTFOaEUscBDPcnmTQmEKRHtqOeW0/HqpSeeQW3jRIRXFeIpoNYI71Wc26/3Dx+SOenoXOot2cpX7cJ5dXuswRRhJcXLnK4WiszgHZg1uHdD12Rsr8NM4jb1xfjV0/nLBWKT6PL60FffYN8UTKoQH08tXL+VhZbUktFl4MJaAcF8Q21QrPq/5miVn7Aa6U=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
