---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAKAM6ErOS62pskkxxsm7tWe/DbZLqoVrpWvZZ9GR5AUwAAi6G7wmei+qRbGZNOEAXpQR1BQ3hfkFEHWChoPNfQyw/1y1re6Vs+IpU0Asf9741ISQrR8majUjR9+idRabYyUqZWhMMmTB7dE/f0B10iYg2HDvAZ1SYYtjVW24meLz9tNM3tYjR0FjnXlhTz+EwxyCwvqt9ciuKbpP5Bpl9Mta/FXKnRRvEqCHUxTLMImVv9lTnLPfzADN7x2fOzMmv+s/AQ39HgKO1zvO2z382LdxbGgnwtVcFwqCuAR9xMgKwwj13QZUrbLSc4RrygZ/p0Yc9DjQYR2BvytHH9XHmjbrHyQupghHr2E+FbRwPwXYjTuJmE82H0GIGp51gwHdQTkFth2pey/J12iwhdh4F4osUV8lUAoTDs0dleOQZmzz+bckHOE3bxg6jHEogr4Ms1yxQUpW9tJUlRpjyo04ax9v9FIZ9I+1wPW6ENo/tEkEsFA5dYMFTWajI8b4P6yA680B6dtGsbvCEZzgSZI8OMXyIO1rMRiSerY0sQyVplrtCd5UM70CcWjndiA014Ce0tB0Wr3hZgW5Zp5TcROD3zB1dapn2Zr/Qsr5qXQKkF128C3xuzFbMO35Bf/7rT7nE413sobHZd1tOVmo57gAherTZo3REkwj94TrUlgjXPE00MPEZcne71Xchi9yFN8i2u24j6bCSLBt9tQ96uvpCRLpJCnsr2JVALcl61t4iO53gVlqN82qKOLq0nqrEBuDmcn0irkxTdWa3Sj7IuSCtozhcNvmqL+VqvM7qEuBql+ilVmjYvGe4yagXHbGH3i3FpDzbOamTsyHBxTy5j6NoHe+M/BktFu4HTSiyKmvF90BXds9EJzlo04bsyrPQXDlXjHwsyvjTRzL465o9NaD7NQXD9J/q3f5fWzvofmVRfIK+r4nW61d1rByAfhDm3DklqPEwlMoDtdhzlVvE8cx2yk8RuuEm2g5fKaZMnV1o8foWDGb4xdGc=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
