---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgB1biqMbsSmd51OSfmm5gnVTnfjlwpV76TogViOq62D8eZYu5q6tDyZAHRTFWg/cKh3zQ2dE9DAzGdzDp3P7bJUdHik64zQx9u4ePfJeODrj81XWJJAcMDKCHEOvpeT9JIDbSqWMN2twqf9BHX0EEdmZ/VGXDar3Ysc/hA/xCQSMGKv4R4AzhFfvRNY2MSEwm0tps/7d/Ufn3kVwGTXwD/Z7FSA5xLt1unTLeKjqjRgf+dqliiX+eOddPTcqCe6bWlE3hpa/OOUqGbNzLflnnRDUHvXDqd0a3iaxfVyJh1IHdhpKpXvPehreaabLCYEoD9JvK61CQ+rH9akISbDCY6dzWzRnIMJvTq4g7VdGUhRvuHyUoqlGyZhJj6o4T9cTrBYv1l7ctE/I/lWgv0ezPWBIYI3zOXsE0L1avwzp3zvdBt6cyPZSFKNyotJ+W8HiNfd5FGq0VOPFUuc7UOXX+P7P8Z2IkDPr81PV7gXZwdz6R3tidR/cEgPRoTFS+7h5SVMwaP5dCd8FheJ9DtNzmdBmCC7r5EgpUGGixaWSceB3QATxBckix62PlCeL1qiopfoZL44Oy+6u4TP/XB2kQSpdCjJ+kxRhodww58mw030tuIMW2W/cMgpb1UK6vfJWBGRxDjVXIgDWPPHIO2pGGHf8ztD7HG9ANMsH4qeZ/ZCMSVBwrlh63Az/p73Z+kg2hLZafdOVKd/yen77YhkwYGu8TI53Hm7tjHhUC57oEYN0dlRcCUpIq16IWpwOqayGa9vDqxEgpIMoyuzm5kUbazWQYhhyG0OvuO5WQ3/nB9WyGxy0MjN9UlXyFN5DLVWIU3Acl0x6lnSiX3pYOlYp2d5AXZOFXRVIcfF86U1Xs1+6s6yvwAfXdS5crw0+cxNxpREtDG/ku4cP+h+nXJNC1QsZXP4Q8gceztD04qilUCFMYmKt/dt2tNUB3jPNG+Kcqn8sZ4897w20Qf1/H6d3ij+oB1zlQ64hgA9WX1E+pWC912D/BpFoLw=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
