---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgAwGEQWze2SGa4uox4UIP2nyGetJHc5xc0Wea3Tvq6cfQMBsINzzqPsgnXn8X3CCesFCvFSbm9AhN7xwphhYLn4nr2p/y+SbMq3AubjJ+Lsgl62/Ejo++h26wgszCQN7WN63N2Pa/GbW0LzvVZmQkvyWH76Q//G313VQHwd20YgRxpkTScTOFcR2vumf9pI6NzgXRLX1PLoSLu2is+nAW8cuDXxTGN8ftRQis9yRFqPvqbKZJmStXR2e4pbOBYqBDEhW8R8Je1O2Oy4KnPvh2jdPQhixqIZdeAGVgPHPa5X/jtZkJWh7Kn0pl7c2qm63M8OuKYKZH0znXLYknaOpN0HNC/5ALdrujE5/oNBEwoxcUgRoDkWXZUr+AiNBCOV9zrl555clniUMdnWxR/MtpAXbpLOYMTKmUmAe+F9Xw+Y0+tCgYHHwNqQJqF1m7uWOBBEVBAIeR1XvZ0zJBwgn/YmPkKZsJz2+wB2Ojn5eVDI594hrR1dIPwpL+j9rQmLkoqzoo5ZVgObH52IYCbpVdn4mgyTaOwpzgvSOZYc4zNYHv3cfGFW6U5KKk7MzkFpGxSaekSXT24+ptSC2lUBoxfSjMnO+pE5UM0uffquEI28BfIdWT+J0jXGhUF97HJ4m+tSEztkNgW3h6VLDyi6ITSMCbxVXIuIE7UjOG7j1N1sa2vhd4YH3qbzlEZ271gmpTxMN6z3K9pbLCoC98qSb1q+4Zrb4pjjS1JTDoyPoFLcUoNvatymyI3XcuNKOqW24A8y0UqwHlVY3WdLtbU8CfvGVeJ4utuqmZpTtPIn1PqXKwXYRicrnNndLqBDm0gTMZTlXL6EPh8AAhyb+GIM7ioxnE26qSvBRlcFXDSssxV+k4MhcDRmmTLlUIDjRt+lCC+P2x7AvfdyBfDOxopArhn853IEWysdTGOJeuOkh8tPsQnMeSa8V3peg5fpi19coKTwA2KGA71qAsQ6OOp/jvVpm0n98u9NKhrb+0Zhys/I4zhtuNElOhk=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
