---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: services
spec:
  encryptedData:
    .dockerconfigjson: AgBDS9364W7QxZD87P1ld4H/NlONH4spe3uzJcB9olikCQh3slvwZTBGuOc5MNiTU55C6vhjJG61KFSAgw8YSUGnj+fw28ZGFTmx6QJpiZyc3Xauk7dr21uIxxdk+7jJo2zgZC9Ujh6sibjp3a2bB6PbF2TW4REvocq+xELb9jaIZ9dAb/Dfora3kyM7PaeOOC2C82R0JOfhGMPEdMQnh1DKRnOTJ17+lnhiInYZXelqf18Cx5ChZWXr9Ga+U7nNWjzsuXh+R7EFX/g5uOtN2vSLwq2X+6ovgAy9bSO+eZVubzBoQXrZ7pktU62N5FgDqA4GOebh6EtaFOnrtGw5gVRyAtOO5jgektGlyAyRTCjYVC4IyRTzv32jkOJThV/S3XmEta01SCzmbwGANVEwgZvQb2cFUmLH6PjS9HQ/pW2KfYL3ekbIH/AhGb7Ilpk7M+y3arFvZ4gcawXsEAoRmgrh5kCXZbMjBZh5deUOmqmybtINnLky+9D2GxHSeP9d8LX3UHnI3Uky/9KTnlGKx5vgBbvQ69rSslzKPAkfaGjJ0CUdzWJL+5xuiFdNE9g9zwiudGdOooISCbuKFvHH5Q18ytuvbPFnxbLLPLlnMWUZAvFoVZ7tj1aEw+ybRCwDW+4VRFpkyyMSOXOqUpC8C+pO0lAM7B7I5SlbXBcmYk5t3UA0km87WL1J5ZHNkmxzw/Ny/91mfA4IlzBhrA2gOvXa3/UKNumMXuZE5grOBbW3cginkgezf47FT8mbK96IKsnmbHJB4WKe2VexU3mmBLHraCOzN/NiX/ZSwqH7J6cFtADJ6bbba4W2KC80mxdrL3mudmFHOPHEHy/B1UyZBb+DTk3kgHTTw443qFpqLavTDSaEIFbeoamD1sjHyEG0zmTllybo2F+hoGquWMp6WLA2IIE6yj8OoxR6e8uIunzJP0C9D73o5u+oKX2ed7oGM+C5iLkAtCxKZJTkfF6rg/ql6Or/HRAxeN6gBmwgvRDxZ4d/fkdd+NE=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: services
    type: kubernetes.io/dockerconfigjson
