---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgB21E2rENu+LxYjtvwKOr3dSPUh44weGkxwVqmhGcwpd2P5202SwBmmCdl8pxVyfonrwyCiJSthkp42L/9hcqZj81PnBxAehmjy2W3jHkT6RUEbi+U+mth/etEYTAIbPf4lJ7j3Fp/u4KfO8wKix8azno0k02rPHYZaHdB5kA470asnS5eELHFWki/IwIj9Mnle67S8M3QyLVviTkwH5DCL+YZCzPK1CIbzevMy+u6AEqhYuzw/cbN83pjcyqY/zkrDmNuaEIoXZEe6U9kHfO/e/iznAO3P2ltfM2q+3i53wGnppcYJxCRDpbfdWUzaLMCM83xT54/NxSsRsVHR2SVzy+56Y+NAc0OKmnjz3DjxVQqvuiRc2Keum1hCaLkUDLt78kojUXTm0Xt7I8+bDlphYzc0NbgRF3KefOjunz8ft/METLYFTI7wQHt6tBbz/x5msEC0z/9PB7P8r8rdBB1cMUyqIKg5eV9QgeOQD+JYW/Lpc4Q1ETHEGxHL2nNiuKrFK3XE/XMx90btv6WwzQA8GQ95EF4iYo/K2t51NITy/lLVHJyCk2no3Xc2gHitRckn+qmZDXsIX3WggmMW9VdrC6LSJkAOgcj2hnXpVIUGKnxDPGiOecOVCWx2Abb40NgFM/o+P3C4HvCswr8xy68DfyFPewyhMl+wdJjF+ndbVjf4nm38AS5ierngEHOcTOsCWsDIf2sorikIA9cHeveEHRMp9Kb2wd4U0TsTBaM+fRYJgZrzI5MV7OBk59eSqiYGwfZiLNLv7D1XdfiOQX+8YEMfr8M+/cvfaHtSRo2Gm5UAep3g5zxar19SsLGhJKDNnL+79G6SnojclFzOFd2dq6QzVS6NINQhUI157i5R0K6TezapSZfAnHK2JcdBMoYcNQ4aiWe5xrgwnwU3gmcC8gjzNn1bRsFLBiF6xogeFe94aRPaAA0ZIjYeQ9G4/qei3xlzNeQOgWV80gj4UpnUGm4Vcgf5H1PVtuJlU8dCJdbVTQ2kkdM=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
