---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCBD1U9fVOWf2BfKHPZvW1/IALHyxAyHz3DGzrQ8dwri/fmI9VbOdxm03Mr2A9aU8nz0mUNuJj4omhwm3e+rqfXwcPKKVQKJgkEZaQnVIKuUxkJYm5LbgplAPYuXUxgwTQYcOmvyHkXWSFty5vm73nx5okeIjwKsoTyKawP6cZnz3QmuZDX7weGdYd8cKpC9YDmuIcY7KpeJ0pCoUBbmWy41soea/tKOvSUqxj5km/73yEi7w+anQjGltp1zTXe0TWyTzM06eSwFYqTmjAl1s4oAXHAVUVQ5XFmysDWg1rrzIRdoJu7wsChwCcrbhx9jV4ikP14SiH1NKRTMni8kpX4q5NArB8/cCOxQb7olopu7G+927umKpwJnbImRkisiPttBxH9cs76J7DrU6l86dVwHJECoqRIgxEjr8z67rJfMHUEVRGXxj1J4hOnQqD2ChymjJK/eRDPhs6hX0ot4ZdlGbSqV6Qw32p/IX2jyR5SMO44Gtpba40wK3KhV4Htnh8RBEATMskxBtr4LhBJ1UcrkUws83DXuVrtkkVD4/+ATlFxTtgT26WmN6+ebwC7amfL35cYGDPi8rkd4b/ClyI/CWayrbG/ZelgVlw7BVeQu9PfPA97xzW0pMEOmF5RsSB/cFvety5D7Jm3S08U6d0e165cDXLOzxmz85d4bnsv/Um09u1/WwM+tjHIwlIASoSGx/rvRrSNV2r0eRkFFnvURdDi9befjsEClm+liS+iaXu5g7gNXZUbZMpUlRaVWlE2MWjqNcm+svElhDCvUpG/rL3Am0XuCinM+CKQ/PpWw83kuCoMdsW9YkXVg0S5ocG+Z/kuEap+hNQIPUQLp/jJ2WD5kmIPFcXcL0CyO8QsjMV/2xNIeqocLwg5JRva8Zk4qp0PzpQ0lfJOKhQ+k4Hssuc9Kux0sw0zQTxXQbwjw3KfgNHdZfk8py5eoTEYCoUzEK7SW8vbfDGcKBwS1YeMMfAH5Reuv4Ci8yDTC324LbmYaOsNoeo=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
