---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBcMnpEhQ9r/PJOlB92n4i88HDeo3jvdo/aJr9fkvPxVFi+HeB1iu1Fnrf/DGbxYlxsLc/vT9R4TkXbAL1pcAJyeNJz909+7PIBN1o0PEB116w8BC2slDt4rkDLzGpLZZjlqYXFiIh8w4HKQ77/SKZidrQrMNeErrztttHDqugDm3LpbSwOuGvrhkVzRABX1wGdd/QswrHHbohBMVHTh21RLsnKmGjuymemiM1HFziRezDZTTOXmGXGWREHr/WoWsukX3/F59si8RdwVPUg2gNl+C/v0RyMVDTwFYhYDsBswKcbP515Ex282xtRIT5UruyFe+f+VLr7QBjLMu3rOpFbaB5yRHno5XRf2XEvg51p++1M9nPfSmmNtgeQ/Vnp52uIcIXnJyYSOOeCZvlpk/IPG8tbztBOMUB6qiRM23BldhMdP0+8GZg2fzE80KzQU49Uj0jQa912DZPKTgY8rX7LdIZ/Gz/Bb3Fk+EHZ3k0ZPAiNH9mNTNw4uIuUMXk8nM3Ds+EV4JjAxk4jcnHR6oSx7FW523cz1Q6RKTb15ky+WwFX6EoWJ5Gn/toswl5inFaxl17fo+nRgwK4Ez5HDrjWtTf2fhIlPW8WNrVWt0b26hm4173jC50/Zhfhq5Ehne4DSfGHJy4qhwouhJ2tkoVSXkCGt44F7IT199d9de5wyvg6q83Ku3ekYfcivHtp4VeTSoxrqM4tQVPIqT+AgUQ3i+sHugIzpAOv/ZQrCwm5wrjZBruAVS4iCSzTORrhf4cl8oTe9EdkZ0mnXTmfttUqTfeIlwK7HkDxvdmXLyXADs4=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
