---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAoAUU3Op0er4c8JDRAsXbhzdy4TcAwFZYhKJuDPr3Dy9X0kV65LGVFrO3aynfRIoiREvapbFwHmGtcQ43QvxcBVlhepvM4eZPAzAp1MCJFhEP7nYVnbotYQg0loNX5Q5uGds1nvOJV173eIYruzhe34wldyefx/KCLCxJ7TpFt4aXssKqBkSS3M2O1me+bU5tyeESIJeCm2UXUI5fFDyuoWiDpOgeOg2F1JOT4lPtVJIeqj9TK6Nc/KD59QfDm5Cke0q6wbnOgnnSMxWelth/2c6ybz4rBRj1tbJ/2l5O6zhm34FfxRtcBrGmd83cHcfbWdhgkr8Jnv5dYHG88muQEwORVkGK9HjrJd0s9CNuw5ux3ICqEHn173H/+iAylkFaGw8e4IPOcqjvwkDcK3oTae8YzXSE8tqoeXnDGrG1IO8zmlNxAu7oleHgi6dYzzhbKbficN/NCF25dRxnOOEhx9R5ho0wOvybwE21WB8Nati7Kn6Mgxzz6SMyEdd+lFH8zmJ7FRcwSuM5FdTYb3/5uWj7tcFoc0ge92crKvWOuhfNW6oNSSs6mw88yo+LrXOe+CWiKbeSJ6TuzvkSQW0nT6bB4OPnqe4OBgWdZPEdF81ZZ1jxO+CewP1ZZjIakH5TNYT55PusJOdWAN397G+mpeXtuaIr6z397l9S/GkV+DSu06wqAjyAJVeRKV8P+icv/wWVCui9pRENERTuNEEwR8UHn46ykqA2WWJmk1evsEpSQ2Il+8y7kylvM1B7sD38KprSFfZoj9oTgTzGYuqtv5AF/JLSr6yhIPUo1cggRbaw=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
