---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBAQOfHxm2oD2nz2qg6ETWrvub1hqlrhDzYG/5qU49vTaOKs55JOZZENnjgvRMTPW93nHB8Yee8JGVRTpI11Jj0Y2uYwQ4mGxwoLC+zjWwWFM2E+XA5ndWVz2gHlgKKfl22aTA33Kj4zffVcifvJLzkKlB3StZdWa1LS3HRiLztdjLCT8pYI7CyphVc3udbZTFevqYg0vFz2cBV6gQjN00LzJ5MNd1/7YPsHjV3wUdE7gZ52TEWO2FT9Q//OUHp3gI07Hr7fMoRH0B2qiAK9kVtizdSrzKdLvk8WGAQbELbA/psOkuGXvj1pBhpZJ2CBuEuTCQEMVJYL8d2JE0q/z0GZs9bfADIOVe64NJUl4my4n6t5IL+UKAd0kLPn9PQXRF/ouUk0dIr4Cxnszd2R8SiGcdGhCzTGb+d5Mh+Eqr61AB7l50hVLgG14kA6edofuy1/55XhLt9npkPCmzjVapaBz4TVin0BsEgfhfrSbLqrC009FQfEbRmF5RyloWaXGIhqaTX7devJwLOKU9FuCrPoL/rucuPOpGCJot48HjbRTtBFPBw6ZHIzb23Zi+nkqpuI01MVDIs7Q1iooA2l1Yx2eux5GDhBcwg1YPWilU6dmqVIYhMOYycGGMF4HIwqqXKU0g3Hjv3zmF0O2bK+BVLtUy/aAIoDf/jdZ2boTkvbDSkqzLV7m9meFmphw2im5fv1PL4e+QoU1ep20PSTeQZwVe+JWtDXYLgvvdVGQskLxNHysbTXtJjWKQC737Xy8T3GiZlproODSEJ3dVoXPFuuoRMZDUHhd0XF4pRHhQwVG4=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
