---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAL70/TtHwiqnHgx+DQ9WCvfM+G0EJheIottPe1JIv1FRb7uOs2faHhidDe73KoZgKrAX6zzswo3uISZAjt5jr8qXvEvbZ9LkaG2vJuM0lNsjWH5P28NOk+fNZ6OVVcUX0SAVIY7ri+sfbmeY6LQrQoo4Hv0rq2g3pMazYS1IfXwb6Tqyyvw7He6Xtzp5Fk8T577spjFAo8P2/7/4ZApuvYy7p5Rth9Dr6US8pkbjZ+jhWnGbv5P2o/v2DZnahsBIDryWCGoSXT+UWY3nuR1f1aOd30hck8zs27ButBLEn1GAfC48+Xy0CAc6r2cBzRL2UICXgOZ2Aq4/1UHWAIqVDK/5sKRarzSl/UgrsN92D1pasB6iDUf3lk+vRohNikIw9US0E6v6zCDKZKb188A+yYezME53bXK8k9uowYfnL8iDwWvm+MD92m9I6NoYQv6ylvC4ScC6Eo+YaA9IfqeEpEFd4FwNetx76ZBDp6lIf+ZCJs2tjjprCk4U7T+0Vx9ESw4P2cKaHruEmkNPj1DiIWMaHIB8l1Tg+TYdJSq0o/DvZeU8VQV2pSQ0kxAkadg4dilLCtIP40MbFGE1jjKdABBZpefsViotO27sQIogqkX+4vSKjF5B9DwQI3lQxLvVnBVXCk4msG9CYWJeSJ77DHUhBWSX9WdxWEbjc5yOF+6vdp8XL4AtSXnX42XTa4/915k8+RRNJ0k5fGih0RX/xAd0mln5rQ/Q5JoAObbI8U+3qj6rY8o38mdNuHIR6DvCrW/fD1DY8/tgw2ey0w/42/KYwm/4DXnY+ru6IdW8BGiM0=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
