---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCbAdMlJtq5uffPh0zSuKAJjo1RQINHr/ktqcfeOBBieqO+dkyt8DJK6GgyqxnMxO6kBJP5pnFSYICIVID1cZuqVTGQ+ZHE3G5MQJznmb+siUsVdzJdFLOppC+3ZtWs6BlAJuLAWoZdY73Lk3Lh0Ytu69lyB1I6t2riuCFL1fwE1/X2tmc46dY6X8I891+NF0WqmQGrOIXDqhJfyuwsJLaFYWpxViuZvsZ3v60GpzmTNLJyEFop0ubjH8zG0arzEWL6bNbY1oWVticG02uyYhOT/pX09U1wswETiXSWdlgbFL7g42ZAv0w5uvKaZY4ZtSV8aFRx7Fx/CbW68FqECqfENeD1yoH52kcfv1fudhQNQEI6GygsxghTwUfGRMB3VMXyCYrwa4Loa1AyVT5oqugy1i5hD3ceUmJCg6i1HSfj6JRCigpwpswZ8ydILCSsUQ4vpoUzEk4O8w/HiIQFMAIaA8/W8G5BbC7SQr552XbWY3SZga95mTH2bVOYd4uy7csCeh5d58UD51QNPkTvYgEyz84DLAEFeEUY8XmJ7w9zkez5YWv696UPORGpENw2bDYOgVOtXuvUUYfNpXZxfjpLONszGJgULfnLwLVaap+iLdHgi4QsVhYSsWDIhALc8/EQEvwqzNSMoA4gATAXHuT/sW8mMJfPDbOtl/x9MFjQIleBn6o5RMl1Pei0BzCz9QKnoWViTBbwdOgzJUHAw9X4kcV2Rkg25+4p3BIteVPp6WWbHF4s38DD4NcEI4MpRhYPpvQU2KJEmpQjoahW1fthZLf75Nf+jZPEf76jyDkvCuI=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
