---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgABFMGV8W29GZYD7odgsoI2AiR/yES/C1S3HCpqIiMFdXV6777nfV89LRY/C0q8izLK0AqSlJY1FMGok2PFedFP8LC4OLSCFlJyyOGxDP5Tst1LWeMhtdbHSFXlwOQVpYbtsIqOzBjSeaG7OZB/kJ1Dz2IRapvatuHIuOfoevxGjVXyt6K7TzdTKK6T8eu0702lWTYPT0T467W6xinzG+2sKstVx2z14Fay1F1raKYJZ7JrchDkaMOiTzwTiFr/uZRF9uZTTzeU/dR+lcs0Vdw1ESZBAdHeHZgoAkRNCTyo96TOfEamzqEUz1acr+zqhbs3tNDhCCsKrdPRN4JHf9CGWXn/2OJmBWjByIB/lz4IgCUUmwUrwVEYJxFtZjPZs12dpeAIBOYSzYg9/rVqAEMnnVLPbb1gq9vCzP/8Tkcz92CFl2b462NX8UmD+1ia+Jt9jAjuH7U6ztjAftvMP4+zutsOb/+ZuB1vLrnI9oC51ca1sJLuxQRKJmhuvPYHy5EdPzrFF7sxwGIEVeeCT8fTFALyb6kDPePS5YO7e29XP16pX+5uX1qiE3XGZpx4/rVV92lR+WyXR3RAP0lEvmhYn3+Y8PpRQouxO+9xbulUmbE5V4iZe4qpRroj47DGc2w/5UvJHVQEWPepLhf5D050CG3wP6QM1pbQi9Fkr3sTsjHLD5rf7+C4uNc2qGtmoDLrzqFn0NaHreI/g1qwZ5uGrOb2eqtlLpwcsKjQQIsePIa1H2cPcHssCezxGdWTrsqzYIBo6Qk1NBFRsc0lLWSq0hSTHPiZEatVGfvznJXLkb4=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
