---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAHaQUADzNhNOBAat93BR695X3ysSx5XlR9r+P7OpELKBsDwCszci4QmX5R1j0SKIPrQ8nzl5m0jh1v/6CjFIeOyKZXrxWOBZvAzos+brMG4PD7wgXEP6a8OlKLfqm40tzXNHj5Qk1wthG9Maudps7YQpRgThhjuw6wiDZSVicAxNg2Tcaq/O01LA6wD4djQEzCyQ3nnp8MaS01+5TkTVFoYUlk9JIPNI2PNd4B76ZJxEvl7DrTUVVlFOhLP4nGMi5TVUIPxFtoRqSUhKjjJqu0642ju47emzLKC34cTK+AQIMCk7SnHXzCQ74M26tdzzQq7rLUddKSKbhiPyT82nc0rjer0pMACcT91M/flikTgUAmFrDvXEave0AEla3UfCPMUQb0Sfu9bzvQS6xb+6nMs6xFDR8E5Jr2VZZaK6EwXaXUpSxdGOnwS03obs0hPVuxv+szmXyslQ6oZ50tYe/KHJp6j2YfpaexxwvaBOzFsQIfs7JKuRV0TOTGLfSg8B+Kc/sLof6XBlu9cw3BfuI9kePlAUKfrsOwPRBcq19JiDj5cR3cCo3NwG66ICD11kVL85tLk9it6HQDbLNVSpQCYtpFTPE19rD5hXqQxBBNo1oZ7hOLcFXJmKPqlyTSjD4R83lw3AK4rFTTX9X7zAjqCzhtWhyluspNBbO44vXEpPd/8n9IyDrhaBwEUnDwhV/HVBv/QhbmukkT8RN+qdOT3G36Dqcx7MK1mNwJcn7fK34e4G/WJr6c2ffegniUe4mCRywdukpO4V7ST2GM6xz4xyiBdvZ/47rm6pqrGNELr/E=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
