---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgBuRVqk7G1CWjfrI6H9kS+adgEq2BFKSF2K/KLDoQB6LhN+fNgHyE2MLX2wavQeFoLCEQLcB58caMJJ/q7Hr0VndotsqG8yc0ugnUT509M8EolfIpuj7FDxEElBJ3sjqKn9uLs3K5pr7mdqNBM4Vt3K65lyaa2pzQFrRSjs+IIHw454mII4RJZPjGodAk70bULfYrGqBueuYfzICZ83zStNl64peuPU1LR1LBNQr5cC4AFZWtaNiJXXKE5BOLHGaS8BOeha7Gpq97JR3opPLJk6vXTy94bu8iJwBYqelkZOyrer25NDBoAtMEZsbZTa3n5gr8mW5GbtR2eCAi/nfaz5UnNHC2vNleb5oX3c7FXXHRPOfgOONG0L6U15lcpxh/Vg4smkU8enrF5LPOcAgdQEUcfJw8df4TFdFNQBIHGxY5wa65ivVQvbnRZIh6GK8dT6VLhHQjYQMgej6BKQ8BLNfDlOrYuGLBgo9eWQhYznpPMhUkRtLyliwXV/IdK5xEViglZ+gIlxHm6ucuzKKghD7lY1BYL3IZvl8w60oPwouTD4TgI/dPpkZ9sIzjsZ4Mb1S08og6binxmdKfpZXBs7d15WUWiUc5ByWwvbkW3wrVN4sGIaR1Y0s+MY2Bsei7uyH/OzhzG6bll+Gjn+pruxzpc7J/T5s/D5LuOrrRytLDwdheZWs3guyUixlNQO2+6XM2VZWayr8da9DOcSNuusnDtCRqNBrXEmsJs9rv6w5mBtXXKnUuiwKcERfziUwC7j1li5hf9kVZVE6Jv6T/fbrlqH0BYv6XGvsAnboaOLV18=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
