---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgArLQO5JvZvKC2WPhJRqx7Gfc7LdCbkEbCagQ1d38r1F7az/PMOUbblvtOU893CV0d3qd/pxa2t0b4i/SJCSEzPfPddNTtNO9PMjSyMPdUO0+Z6wSUDzsgCAI5ZQXF4d93RB+ZquU0UiXcF3R1PNwt1X6BMXt13mySYF0LtZR/iwNyCAkiD8QookXTG84EUrGPH7gzAi9pm0ffWjJQS9L8p5YfkKevQKhg712gbnpMyKCpbcyCxzaHXD1gaxocpVmC/q0dRw8m8Xy8sZ7k5qTIcxF+WpgAw5oCS8ueQ7ZWYbp9GIPVl7GF6ZIUcekEKJBgZdd2qG58+aKivgmQpGrOouHxr3A3kkE/XHdaGogwPykgHTEAbbdtaRfHwstsgEzfkyflx22tHDdijns0vMVeqMktChIJYdXahDeJveZrqlOFCYY1Wa6ccUK5fYddpWu5Yw9JsAF4TD2DMb1FwG+R+8Fwl8VIN3VGUmf3yKzPU2vs7sZFqZZO1BfTjTRU8Fw9JX/hIlFq0ziNCNpu2W22FYcxc31AoF3Fxp5j1YrnQ6dZrP+d5T9oCrqB2OgtM6iS76YZAPWyd0Rhks3PJVLCMnMVifTF0oQP6Ye5NKjE827ApC/f7OCXGyBIhTksUZUN86uiffEnFsNSAc8ep+NafRl2eoCdltEHVWE2vINQLNdSuVGf6/3gusulIE470+YWGfmRb8/TQJ/3rCTH0JC3ZRRIgGysBWQqzQGcC4w8XCOd4k70JItAVwTMzouO000wxSEvVCXi9H0VBtyHB11C/3s84DvTiCSh34T6CYnwGojY=
  template:
    metadata:
      creationTimestamp: null
      name: slack-url
      namespace: flux-system
    type: Opaque
