---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBNs4X4a7zSXdYpyNBu8xwcHb+gzhvotkoKzsB44+1DdzIFeaLhkjxac7/Ubq2vrWFqY+mfX2JXRgW9U15UMJiBgm5TTTUwQGhlGwLRh0lqoy+UrF/bzWx958+qQJ8u3l7KUvIzy9YM8XTYX8bbeJ1U7F/PkkKQtuoG32wK/MJtq0+j9ECYZ38rGjIf7tYHBsb4UXsoqWlPvunkJ9ZTBDP2NleGmkRq69y0seAXlZc3N3gRs3DdVe99zdqmVC1X9yd9VJBQFP10VuWyPZ/OAGndYuUamJAUIMrCIwzSaSrw8dR8PoaW4cJ8DAgyx9yMEtdOWj+YVp0AYLOaAY1gpzfRp0qIbkEIHJBczJGma0rcqmYnjibp8PxaNTIj2s0YKLloLqkNlDO4bfarEZT9GKlyIty6r439V91/0AAH4FdeSiJqkDtbjy7Uqtf/6ultw7igtgMIJenGeUTURWtptHJ2XioeF+pSVw2DiwIHxn5k75SaEL61qWwx9DWFSRO33m3jP3bWlIwWyCLcC/Itn7wO5sGEUYMBqRqBhV3d5hMbSiu1J53jtDu+x09lB4Bj7ngXImGyFvTkF+04P+ISL5MyM6VnTMruD/yzEhW/SU3ZwmnIDQQWTwV0yLkiUD4cyfdz9mRTYJZQbOKyF7tyS6sTU2Dm8mgRyth1kfLKC9rq1S3ypvxFGKG2aHHKL3WFKNymlAsGoa4yTb0EZLNZXeang9n7/ENL/0u3XqvbYIImow4f6zJR0QSm
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
