---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCaulKLlm6o9FKYnycqfs5a357HAryy5WJLJpaDdd2ObZnhi+FecNI4beYBWmPR8g6QFfs07412RlCl8YLBs1tfRS2tfSk9sjanquCAVqzLc3KGl3RXbEaXfu34jKHDP62KkRy+IdwLY6ovQvmN6NR921UAFfi4RK4MHJFW9U1WzoXtyzs4xPy3pL/eZM9eugKOCDqoc1by/TUKqmssIUtqqe75Q0rKt+dMCJAsf6szXkSPoGwT5Zeq0ajJ6glwc/gX30kk/sYLhNBhCQXubynOhuFklE88jZbxp9/EDGngvs/R7xTQmYTKW7Q+74G6A1G3aRIICFj5RHlm5LNW+qRKUh+k2kZSChS9FdCXAbBU0LXVQLyaIyLrKmCYbBHCT/eJoi7cf3p+sNGY16WQiBhH4qV6LWDStFskHQot1SlDdVwWnY21SCp7pMsRVtY5d1Nmo1CuFTjDWUNlbjfyJYxkjEh3K2mDSS9y3sByQfNHcY3UR9B4OjIS+jkBofN/HJupowZ9HWdh9EljQQnoaQdJyV4aEM9XMBa7lC8F4HdLxg6TQGKqkIuOqePv8RkL/K+Ttb/PAFSYvydadeCmNj5e1an+oMdcolWm/e1fXOjKo41Mk+zBkDjOUl0dyrmwobaPc0deRNPUCYHYHLr9ijjgicksD8SVz8ZoDOewZIkxZ7hJxq8FzfofetLk8ymDFSmX/YQ2QTITGXQYyyXtdK9MvaKHWebf8sYl0TPQhYxVq26gKOVRN2b+
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
