---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCCC5bX/b7OK0n9OQS/XTQvHb2LpfIOsoGHFU7247ff/cTARDotptmn5OE9n7LedY7hKBiZ60MQkze0fo0wHWVvIUS7kPjgPd/WDNS4MIecgt/abXDRZI8gH2wf1YvGuER2eacrlZKjiLQstTmCrBbqYXj237bq7k1PTX81q6SyIC9LSfWUB3HbCR0Ki9x1KwtsjQyjbkK3F52z6gBh0FgYFXmunG5ElMRRtgBkwjyPNhcx4wGPZmWcAZflTKGvfoRmm2nqHjeXEye66GLr0K/0kG63oxGJ1mqjzx7oH4mz5bUD7mUOGjW5m8UamvrLrtMO+TDp1XA8iO/1m6tqnmR9GqpmLYkn4w5ZUU6bSdadL21O7/v3hZGCsgZDdYu9gpGzJVND5mN/+9/PAZzxFWYXjnH9SsdngD26OYKo/x97exKwCglBeg2reANIzj1uyRZeN1k7qLTRf/Z21usbuDoFjCkgAhxAEZC48bVqR0iqMDHe23dtB/vYGVTuk92nWbRy9VktN/ORKXnNh9TbxGkD2VDpqH2ib7Y7Ap7Hrz/CdGW2bPsS+qJXW8f8HVTa9EIyV6zFpU5qjINayoDpnfRA/33OSjyf/58x0NZlQuWHxtUueEUH/M5vCo7Jt4XXdgiftBYp773BA150knOnZq4WXpji/bz8cJmPfOp/15C1ozGtExaqszXtvzKLAnZEJOMaw9iK0QcgdYIso6vqZJ/jGu6peLQIfnONv0KBLwjPZLSgCESAFnS5
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
