---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBh7tTU5dYh7DHB3I/MqMmPQXnaiOQgVTPs971r0mhD1vZeMrFtP5/yLKf37DBquSaQz6n4OeORL9q/mp6tZQcP9EGzmpEi9Kq2sklx9we1bv1nkH/WRN3XTIUQX3PyervlgTlXVOpGMzEq2y8I4y8zzz/khTNvBdF9kTJUPBCjqXasIea8f0gurJVoMqbyTLh06C24twHpzyfkpmehUfiCZ9GmgiIiiG5WBkN+faf/dr2sK0uCHkAcPFcxtvb+xyFtGr6ItoOdxQxYxGAIcuyVWSlCRuXlLk78fUclTN1P5Skmdt2/5Jd/cwdLX5rfyij1Xt8aPxSjX5ICdfpqiCAL9nHI75R0j5trHXa3tsXqrN7v4Jn5Oi4aZj0ESBQXGcVKM4F9Y8BEvYe15PTHqcGlIVSYAwBarPV4MTHjmUmlqQT/oFF96xcmMriyD0vFs00+UTtyPKNbjiiGeWoLW94n3YhjiDFqdPIwbZIVvkJY6lE3j7kRxMyNziefPflI5rjccLBkHwY1QzReIeib2xB4wLQkZVYaX8Y+ebXQgmFrvcIUL/4ZtS2Go3ZsTv5Oqj6e8PeadHW3mtFbdRLXEtpSN7PxB7nQVLs/GjIIwu/y8dxmvrfgoxRVed1Y1vGArg8gpPrA8HyixIalkqvjxsa0epI3qaHirTXkYGTmccsYmzVuwp/BgLP2pqIgQiDe/xytFBw25uDKqPNDLM3Dw8fgbBPwwgQVEb41KCS1uwosO1MVHlVyhBiu
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
