---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAGBUBQ1jgaBkf74VsmiCQdDPcMQswWHbW1sG+sGgYdL0T1MPTX0/YiBW40mqlxgRV4opQdVYO1Jl3GgfcRc9j3Sw9hz3LjrfpQUcN7UGVYd/+QMuKnRQ8GhgvmJqrOcp8k9bnF+Ii2MJrE6mHk1JWTOuGNqBlIQPsF2jvf8DDLo98YSIzh0EyRzEMtPyyG7YZi5XVyNXBB2VjyrjVYV5EGPtkQBXCsEhedNbBZOBJCRu4bJVbZyU0nPUhkwkV4N6P1uNqqIwao6Ilfjz0tWKCVbPlZk6tGxfjDg/l4kiFi9EBGtfrpqpzxCIofrHEsvVN/6jDrLHrUFT8UA3/0GdzGomNcsNi3kcL2BK9dedd8IIyeKpgRFr5BlsGvizE2wgCYFP6eu9yzTpgK1yVhSznA6Yr57cWy2F6htfYgbKCkqFz9w7ZdyQrl4knyYWQIVgFfE7gicZ/BHdicmOXAuRdxpSwS55JHDod9Lpob3TjZOZRa1NDnBX4/VqX1OYFMBCaUGukgfv+vni7baCoYWL4uNnIyClHzMC5vOZFzzUuhVR0xVGbCvfIMs4xLx4h1scIozQ/7w35QNRhBOOAFUMgDCG7l/mBJgxukss09htSLaMAn8lrsqgIz13oFqVDKYIRe1JYO3Kiv7AnHsQfNeaTAT8rAvPPTmcqP8VXtIeUxCFMEVVCqqf/p9/PmMS83e2lYAuAusCh/Of24ApEtA+IWRUlf9jZfRVthlYQqauWQcFiNDxmsj8Pe
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
