---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBkozy+l/gcddnf2JY6aMw2SDSlsmNkfhZpL/lsPp5QgkgEgG1HbSidAAfaZ3n3b+NBzGMs6SlWmr4kFb01l6EFcYr3U6lOQQY6zzyEZuHF8e1/UlafxZUD5hUFg/yk2cZVz+GaPc2aciCP0h8flD9OwiLW+EV6o494Yvobd9hdIx5yJTyjGIQT5vPtFS6Y1NME9KpzJhHQvSk0m6HfF/oVaPNdw12nVUVYPloATlmqERC9eOw1nCFdhNii0x/hCRVu5j5bEF+cKQ3FrcE1DuRMaEicCekf1t4/UFs9ya0lCqHOU1Jfr0B+D4ierteFZkUpBgsY8IvsLWMOCZAdc4MWhwpp1Uhv0U9WbsWs8dxUBjr5iXdLgHkdUb0Z+vuuHmb1uuDqaNFT7NGz9l2XQf85SvZZV7aIKqFLWCX1rs0CyQwlBWGr1JhPhUhX3DmMBbZPv9knUrmYI7Pr3CkZ+5KaqSRvp6o759lZUbcHbCPLdk53WDGgmBdfq1MYNtYyxhizJxurmQpyicy3+kEelCcfcJHQxYfWafVgBOh0NJqhE4vBt2C5Kk0Pfl3TpXSDmd6eHiEYEH6t3I6q8ZZRxiRnTAvua393s+RKVx7p1eALI2mTaSr3Yh5F7lg50MVijDSU2vmGyg03TN2YmbkKNygtAGWxJBdGlLofZ6bHgKs+ku6yldz+rjVJMnC0WZP6GJ14oKFwceAYUA2dH7qdZaRuDkC7n90fM9kVIw6IN6QpegeyeKsdI/wt
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
