---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAChCLm0vNsVFnBqH83x3JIEBdYhEd3xBLeTLgIMN1vyumTAHy0mO4PNeYzYDwgEe5A8vR6wTMzhgXSs3oZEFPlxy9gye9l1POaQrGW08vYLGFczjyQ87qCHGzm9tZNMimjffr2Xvh6lEHHj1bFYQXBnrW6UKpPb+9+RXe3WOt9F2pLryl5tJ9JIa1M9mGK5aB1JsuAq3SuRCSbsylZsWIQMMzJiwPVT/1IkMaE5XKlJXjgkxNhrU3hf4G/QfcDI8X2qg6zg1MyJNJpUuaHAqeTy8UktXTCQMB/+0U7hZbJEDUc3yS3LMF9jXRTKAAhxb+lgZGbzr53V02u2OCAe8FVpyFrpm5Hu3PWu/ra5xeg2ZfhcQ4pdrOM4OuC70zj28WC8aP3QZoZ17v5ItUx0oqqfsEIFox4f1OFPamN2Nmli0vQoCUNWFZJqevzRHrW7feuZqiIjRrWGT44iexBMJ5G6Pz9hcAdLivJlchDS7/k/gCFnH5Yl9f+7cgLHWOpiBE/ZAz9kDIf87frvrBH6lPFLRGqdw/8CmEju+meed7DuXPXNVxHTMA34euxZjN5JdtjbCB9e9BiopEHGbwKeDmWUPzrl+UTbhkPBNi6vhvlR7oS3WyFFpqMU0kW1PBHFb6mf/Bf5R4jTqZ7q0uJqFJnHW3VKg4N3+loUmVl9Z4OReRJ0MP00bXPEoPXqz0gvhHtrk4jXfG/5Bxd2cZGKLe3/y7iZpMHsi6Iv5KExrfAWKdT4s/+sp6s
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
