---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgA09XZxagmj3Xdmhwz46enki2ZNH4InStlwA7bk0s5wqRcDGYkrRBAh/kK6IrmJ1Q2Z0gzWaQOb7f+RHc8soybNegwP/OQ15cv2GP99cM20sB60KOJb42VaMni/kEtQuOyODDZ6xzQxkT5r6hcIbgcf6wH2NK25lLociK+oAmRr1wygDDaYcGG7jj/QhK+eWgVvttAQqOBKY06i7XFFKaR+nrU5e4pLe5jLU6fc3cDzwcJBSfo98vUWnv65Izpx68CxljGzfsLb79PFyLCVdSmA9h/Edr9Q+NIcBkrbVDizjAoawIKdYSgOA6a7jKL8840feT4gvHDXv1EoBmGfPnRpsNeft/uACDcJAw/ao6+JoTNZZsUgiKx3WxR0qwqaRFibHfpbGeCKh/YBcrXoPhQN/ZIvVvTQr5uz5ELtGIDFgBS5XLerzF124Od/tDDWHI2qbmCZ6psvW8l/K5+M/Zif/8rTb6298kCzdjoUmgChkKCma05wL1Y4Y+I+YWzn2GSHbcSa0YY01sy7V5EmP5fO0m6FjWOS6qtIUtxIbuRS2F8dVk4uMxCqP0MdLiTpmkBe0Pl9vHYP1Pyz6l/3iQnJ5MNi4uC6S85e8zXU/f4/q43lMTLp3k6P0dXgJgIGvKOUrX4GnTsB0ntB3K/eXnPSbJSaOXZ0YlaVxh7Sqs9ojCljI0LaokI1SC0Pb98uZY8elOpYaqpzVZC/AFEAM4t0WrEBK8i/DmJNclMKOo/PxKvtcuBLEB+M
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
