---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAZqaJK8duEk51Uluo7rc0x6ZWIAo4PJeFXkdi5sihFvtXz2FhJfK5Tx7BsJHo0JW5azMNA8EbE6uFb5D683KEbMvjOoVpGyOCExpS2xRTXx2tpQY58CnPzHwHv7vYj7jeUKECDsHN+pS0Q0Cqil+3TGNjBHojcXzNMuqMgtVDTELUL/9kZIpkVClpjUy0Cm0pBLaU8p8+lJGUlTBwckuYbi9QbjYbupgKAE4orzoW6zJ19DClKLUjQK7Hxlhjdwla5HeWeSJF988NME3tPSLR2xkIsaofbm7BtYE2Q9YCZ2OzmN0I3PpIf3bwEMlc3zyKYT2lRhMe7yN6CQBqPiletrz6woVfLyBZ5SlRKfmI557eBjAookkBMCSRs0iHjwVN/j9e33vo/4zLdrJjFWeuN6Q4SwKwDQIFpZBEFshl4toGmIVONlWSXq7/ACs3wjRQ7Xh7mhcxpbpp1mYbr6/alfiyaag804D/rRtFo62i19thGBC63n/MkNc56uXeEokVlYE0jYwHc9pOmzmdy5KFFpHsyBLX7VWruFi0xNnVDsjax0OK1CSY3MomCHppszkhs+7NaH6agmVFaoYVV8JRguVbyCy1LDEYWP4xC9yc7K8e6uEQ1VkO3/yZFU3yyvZZo9LsG2Vo9im0bCVXJON8V7iZ0hPcvYZMNgwBXn1wxkmTrR98n086TRxxYxN+MA3mQhOWZIrtUAJ6z2AE/v4Joy0KqyvdeXfAtnJ5eAHV6hD1d62RD/Uq1
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
    type: Opaque
