apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyYmJidWN5bS5ncmE3LmNvbnRhaW5lci1yZWdpc3RyeS5vdmgubmV0Ijp7InVzZXJuYW1lIjoicm9ib3QkaGl2ZS1jb21wdXRlLXJlYWRlciIsInBhc3N3b3JkIjoiODZDcnI4YktDaHZOYmhlODBkTXR5VG14dHQ4WkVuYVIiLCJhdXRoIjoiY205aWIzUWthR2wyWlMxamIyMXdkWFJsTFhKbFlXUmxjam80TmtOeWNqaGlTME5vZGs1aWFHVTRNR1JOZEhsVWJYaDBkRGhhUlc1aFVnPT0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: hivecompute-supply
type: kubernetes.io/dockerconfigjson
